import React,{useState,useEffect,useRef,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Compass,PanelLeftClose,ChevronDown,ChevronRight,Plus,Search,Bell,Sun,Moon,ArrowUp,ArrowRight,Upload,ShieldCheck,Check,CheckCircle2,AlertCircle,FileText,MessageCircle,Layers,Target,Bookmark,Settings,Download,RotateCcw,ExternalLink,Loader2,X,ChevronLeft,ScanEye,Quote,NotebookPen,Calendar,Database,RefreshCw,HelpCircle} from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import Markdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import 'katex/dist/katex.min.css';
import './styles.css';
GlobalWorkerOptions.workerSrc=worker;

let sessionToken='';
async function api(url:string,body?:any,method?:string){
 const form=body instanceof FormData;
 const res=await fetch('/api'+url,{method:method??(body?'POST':'GET'),headers:{...(body&&!form?{'Content-Type':'application/json'}:{}),...(body?{'X-Session-Token':sessionToken}:{})},body:body?(form?body:JSON.stringify(body)):undefined});
 const result=await res.json();if(!res.ok)throw new Error(result.error??'请求失败');return result;
}
function MathText({children,original=false}:{children:string;original?:boolean}){return <Markdown remarkPlugins={[remarkMath]} rehypePlugins={[[rehypeKatex,{throwOnError:false,trust:false,strict:original?'ignore':'error'}]]}>{children}</Markdown>;}
function Modal({title,description,children,open,onClose}:{title:string;description?:string;children:React.ReactNode;open:boolean;onClose:()=>void}){
 return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="modal"><Dialog.Title className="modal-title">{title}</Dialog.Title><Dialog.Description className="modal-description">{description??'请确认内容后保存。'}</Dialog.Description><Dialog.Close className="close icon-button" aria-label="关闭"><X size={19}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function PDFPage({workspace,page,setPage,pages,onVision,reference}:{workspace:string,page:number,setPage:(n:number)=>void,pages:number,onVision:(data:string)=>void,reference?:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(true);
 useEffect(()=>{let cancelled=false;let doc:any;let task:any;setBusy(true);setError('');
 const loading=getDocument({url:`/api/workspaces/${workspace}/pdf?reference=${encodeURIComponent(reference??'')}`});
 loading.promise.then(async pdf=>{doc=pdf;const p=await pdf.getPage(page);if(cancelled)return;const view=p.getViewport({scale:1.8});const c=canvas.current;if(!c)return;c.width=view.width;c.height=view.height;task=p.render({canvasContext:c.getContext('2d')!,canvas:c,viewport:view});await task.promise;if(!cancelled)setBusy(false);}).catch(e=>{if(!cancelled){setError('页面加载失败，请重试。');setBusy(false);}});
 return()=>{cancelled=true;task?.cancel();loading.destroy();};
 },[workspace,page,reference]);
 return <div className="pdf-view"><div className="pdf-toolbar"><span><FileText size={14}/>教材原件</span><div><button className="icon-button" aria-label="上一页" disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft size={17}/></button><span>{page} / {pages}</span><button className="icon-button" aria-label="下一页" disabled={page>=pages} onClick={()=>setPage(page+1)}><ChevronRight size={17}/></button></div><button className="text-button" disabled={busy||!!error} onClick={()=>canvas.current&&onVision(canvas.current.toDataURL('image/png'))}><ScanEye size={15}/>视觉辅助</button></div>{busy&&<div className="loading"><Loader2 className="spin" size={20}/>正在读取原页</div>}{error&&<p className="error">{error}</p>}<canvas ref={canvas} className="pdf-canvas"/></div>;
}
const taskNames:Record<string,string>={IMPORT:'导入教材',VISION:'识别扫描页',VISION_BATCH:'批量识别扫描页',FRAMEWORK:'整理学习框架',GENERATE:'生成教辅并审查',TUTOR:'Tutor检索与审查',STRUCTURE:'整理教材结构',QUESTION:'出题与独立验题',UPDATE_DOWNLOAD:'下载更新',MAINTENANCE_REPAIR:'候选修复',MAINTENANCE_REGISTER:'注册长期维护'};
function FrameworkContents({entries}:{entries:any[]}){return <div className="framework-contents">{entries.filter(e=>e.body?.trim()).map(e=><FrameworkOriginal key={e.id} entry={e}/>)}</div>;}
function FrameworkOriginal({entry}:{entry:any}){const [open,setOpen]=useState(false);return <details className="framework-original" onToggle={e=>setOpen(e.currentTarget.open)}><summary><span className="badge">{entry.kind}</span> {entry.title}</summary>{open&&<div className="prose framework-source-text"><MathText original>{entry.body}</MathText></div>}</details>;}
function App(){
 const [activity,setActivity]=useState<any[]>([]);const [activityOnline,setActivityOnline]=useState(true);
 useEffect(()=>{let gone=false;const refresh=()=>api('/tasks').then(rows=>{if(!gone){setActivity(rows);setActivityOnline(true);}}).catch(()=>{if(!gone)setActivityOnline(false);});refresh();const timer=setInterval(refresh,2000);return()=>{gone=true;clearInterval(timer);};},[]);
 const [ready,setReady]=useState(false);const [version,setVersion]=useState('1.0.0');const [books,setBooks]=useState<any[]>([]);const [book,setBook]=useState<any>(null);const [facts,setFacts]=useState<any[]>([]);const [knowledge,setKnowledge]=useState<any[]>([]);const [audit,setAudit]=useState<any>(null);const [records,setRecords]=useState<any[]>([]);const [diagnosis,setDiagnosis]=useState<any[]>([]);
 const [tab,setTab]=useState('learn');const [kp,setKp]=useState('');const [modal,setModal]=useState('');const [edit,setEdit]=useState<any>(null);const [settings,setSettings]=useState<any>({provider:'DeepSeek',baseUrl:'https://api.deepseek.com',textModel:'',visionModel:'',apiKey:'',timeout:90000,retries:1});const [inbox,setInbox]=useState<any[]>([]);const [updates,setUpdates]=useState<any>(null);const [messages,setMessages]=useState<any[]>([]);const [question,setQuestion]=useState('');const [selection,setSelection]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [source,setSource]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [toast,setToast]=useState('');const [dark,setDark]=useState(localStorage.getItem('theme')==='dark');const [tutorOpen,setTutorOpen]=useState(false);const [recordKind,setRecordKind]=useState('mistake');const [backups,setBackups]=useState<string[]>([]);const [consent,setConsent]=useState(false);const [questions,setQuestions]=useState<any[]>([]);const [structure,setStructure]=useState<any>({edges:[],symbols:[]});const [batch,setBatch]=useState<any>({pages:{},active:null});const [batchFrom,setBatchFrom]=useState(1);const [batchTo,setBatchTo]=useState(3);const [batchConsent,setBatchConsent]=useState(false);const [framework,setFramework]=useState<any>(null);const [sources,setSources]=useState<any[]>([]);const [sourceRef,setSourceRef]=useState('');const [batchRef,setBatchRef]=useState('');
 const file=useRef<HTMLInputElement>(null);const referenceFile=useRef<HTMLInputElement>(null);const chatBottom=useRef<HTMLDivElement>(null);const current=facts.find(f=>f.kp===kp);const article=knowledge.find(k=>k.kp===kp&&k.status==='PUBLISHED');
 const load=useCallback(async(selected=book)=>{const b=await api('/workspaces');setBooks(b);if(selected){const prefix=`/workspaces/${selected.id}`;const [f,k,a,r,d]=await Promise.all([api(prefix+'/facts'),api(prefix+'/knowledge'),api(prefix+'/audit'),api(prefix+'/records'),api(prefix+'/diagnosis')]);setFacts(f);setKnowledge(k);setAudit(a);setRecords(r);setDiagnosis(d);setQuestions(await api(prefix+'/questions'));setStructure(await api(prefix+'/structure'));setFramework(await api(prefix+'/framework'));setSources(await api(prefix+'/sources'));setKp(old=>f.some((x:any)=>x.kp===old)?old:f[0]?.kp??'');}},[book]);
 useEffect(()=>{api('/session').then(async s=>{sessionToken=s.token;setVersion(s.version);setSettings({...await api('/settings'),apiKey:''});const b=await api('/workspaces');setBooks(b);if(b.length)setBook(b[0]);setReady(true);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(book)load(book).catch(e=>setError(e.message));},[book]);
 useEffect(()=>{if(!book)return;let cancelled=false;const refresh=()=>api(`/workspaces/${book.id}/vision-batch?reference=${encodeURIComponent(batchRef)}`).then(x=>{if(!cancelled)setBatch(x);}).catch(()=>{});refresh();const interval=setInterval(refresh,2500);return()=>{cancelled=true;clearInterval(interval);};},[book,batchRef]);
 useEffect(()=>{if(book&&kp)api(`/workspaces/${book.id}/messages/${kp}`).then(setMessages).catch(()=>{});setSelection('');},[book,kp]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light');},[dark]);
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{const element=event.target as HTMLElement;if(event.key==='/'&&!event.ctrlKey&&!event.altKey&&!event.metaKey&&!element.closest('input,textarea,select,[contenteditable=\"true\"]')){event.preventDefault();setModal('search');}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{chatBottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
 async function action(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function poll(task:string){for(;;){const t=await api('/tasks/'+task);setBusy(`${t.kind==='IMPORT'?'正在建立教材工作区':'正在处理'} · ${t.progress}%`);if(t.status==='DONE')return t.result;if(t.status==='FAILED')throw new Error(t.result.error);await new Promise(r=>setTimeout(r,850));}}
 async function importFile(f:File){await action('正在导入教材',async()=>{const form=new FormData();form.append('pdf',f);form.append('title',f.name.replace(/\.pdf$/i,''));const result=await poll((await api('/import',form)).task);const b=await api('/workspaces');setBooks(b);setBook(b.find((x:any)=>x.id===result.workspace));setModal('');setTab('facts');setToast(result.duplicate?'已打开原有教材，学习记录保留。':'教材已导入。先核验事实，再开始学习。');});}
 async function generate(){await action('正在生成并审查教辅',async()=>{const result=await poll((await api(`/workspaces/${book.id}/generate`,{kp,consent})).task);await load();setToast(result.status==='PUBLISHED'?'深度教辅已通过审查。':'内容未通过审查，已保存为待修订。');});}
 async function ask(){if(!question.trim()||!book)return;const q=question;await action('Tutor 正在检索与审查',async()=>{const result=await poll((await api(`/workspaces/${book.id}/tutor`,{kp,question:q,selection,consent})).task);setQuestion('');setMessages(await api(`/workspaces/${book.id}/messages/${kp}`));if(result.status!=='PUBLISHED')setToast('此回答未通过审查，未作为正式学习内容发布。');});}
 function openSource(f:any){setSourceRef(f.source.referenceId??'');setPage(f.source.pdfIndex??1);setSource(true);setModal('source');}
 async function openInbox(){setInbox(await api('/inbox'));setModal('inbox');}
 const navigation=[{id:'learn',icon:BookOpen,label:'教材与学习'},{id:'facts',icon:ShieldCheck,label:'教材核验'},{id:'exercise',icon:Layers,label:'针对练习'},{id:'mistakes',icon:Bookmark,label:'我的错题'},{id:'diagnosis',icon:Target,label:'学习诊断'},{id:'transcript',icon:NotebookPen,label:'课堂笔记'},{id:'review',icon:Calendar,label:'期末复习'}];
 const verified=facts.filter(f=>f.status==='VERIFIED').length;
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('learn');}}><span className="brand-mark">知</span><div><strong>知微</strong><span>CALCULUS WORKBENCH</span></div></a>
   <button className="workspace-picker" onClick={()=>setModal('books')}><span className="workspace-icon"><BookOpen size={18}/></span><span><small>当前教材</small><strong>{book?.title??'开始你的学习'}</strong></span><ChevronDown size={15}/></button>
   <div className="nav-caption">学习空间</div><nav>{navigation.map(n=><button key={n.id} aria-label={n.label} className={'nav-item '+(tab===n.id?'active':'')} onClick={()=>setTab(n.id)}><n.icon size={18}/><span>{n.label}</span>{n.id==='facts'&&facts.length>verified&&<i>{facts.length-verified}</i>}{n.id==='review'&&<small>规划中</small>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="local-status"><span className="status-dot"/><div><strong>资料保存在本机</strong><small>让每一次学习，都有积累</small></div><ShieldCheck size={16}/></div><button className="nav-item" onClick={()=>{setTab('settings');}}><Settings size={18}/><span>设置与数据</span></button><div className="sidebar-foot"><span>V7 · {version}</span><button className="icon-button" aria-label={dark?'切换亮色':'切换暗色'} onClick={()=>setDark(!dark)}>{dark?<Sun size={16}/>:<Moon size={16}/>}</button></div></div>
  </aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>学习工作台</span><ChevronRight size={13}/><strong>{navigation.find(n=>n.id===tab)?.label??'设置与数据'}</strong></div><div className="top-actions"><button className="secondary small" onClick={()=>setModal('activity')}><Loader2 size={15} className={activity.some(t=>['RUNNING','QUEUED'].includes(t.status))?'spin':''}/>任务动态{activity.some(t=>['RUNNING','QUEUED'].includes(t.status))?' · 处理中':''}</button><button className="search-button" onClick={()=>setModal('search')}><Search size={16}/><span>搜索知识点</span><kbd>/</kbd></button><span className="top-divider"/><button className="icon-button notification" aria-label="通知与更新" onClick={()=>openInbox().catch(e=>setError(e.message))}><Bell size={19}/><span/></button><button className="avatar" onClick={()=>setTab('settings')} aria-label="个人设置">学</button></div></header>
   {error&&<div className="error-banner" role="alert"><AlertCircle size={17}/><span>{error}</span><button className="icon-button" aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
   {busy&&<div className="progress-line"><Loader2 size={14} className="spin"/>{busy} · 原始资料会完整保留</div>}
   <div className={'workspace-body '+(tab==='learn'&&book?'has-tutor':'')}>
    <main className="content-area">
    {!ready?<div className="loading"><Loader2 className="spin"/>正在打开工作台</div>:<>
    {tab==='learn'&&!book&&<div className="welcome"><div className="eyebrow"><span/>从自己的教材出发</div><h1>每一个为什么，<br/>都值得弄明白。</h1><p>把教材变成与你一起成长的学习空间。<br/>从概念、证明到解题，一步一步，真正学懂高数。</p><button className="primary large" onClick={()=>setModal('import')}><Plus size={19}/>导入我的教材<ArrowRight size={18}/></button><span className="welcome-note"><ShieldCheck size={14}/>PDF 保存在本机 · 教材事实由你核验</span><div className="welcome-illustration" aria-hidden="true"><div className="math-grid"/><svg viewBox="0 0 400 280"><path className="axis" d="M35 225 H365 M90 260 V28"/><path className="curve" d="M42 207 C95 211 118 206 147 175 S200 71 247 74 S320 142 370 34"/><path className="tangent" d="M100 226 L285 40"/><circle cx="196" cy="128" r="6"/><path className="guide" d="M196 128 V225 M90 128 H196"/></svg><span className="math-label">从直觉，走向严格。</span><span className="math-formula"><MathText>{String.raw`$f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}$`}</MathText></span></div><div className="welcome-steps"><div><span>01</span><strong>建立可信教材</strong><p>保留原文，识别结构，核验数学事实。</p></div><div><span>02</span><strong>沿着疑问深入</strong><p>理解符号、条件，以及每一步为什么。</p></div><div><span>03</span><strong>看见自己的进步</strong><p>用错题与复测，找到下一步学习方向。</p></div></div></div>}
    {book&&tab==='learn'&&<><div className="study-heading"><div><div className="eyebrow">{current?.chapter??book.title}</div><h1>{current?.title??'从教材核验开始'}</h1></div><button className="secondary" onClick={()=>setModal('framework')}><Compass size={15}/>知识框架</button><button className="secondary" onClick={()=>setTab('facts')}><ShieldCheck size={15}/>核验教材</button></div><div className="study-layout"><div className="chapter-list"><div className="section-label">知识导航</div>{facts.length===0?<p className="muted">此教材暂无文字候选，请查看原页并使用视觉辅助或人工录入。</p>:facts.map(f=><button key={f.id} className={kp===f.kp?'selected':''} onClick={()=>setKp(f.kp)}><span className={'tiny-dot '+(f.status==='VERIFIED'?'verified':'')}/><span>{f.title}</span><ChevronRight size={13}/></button>)}</div><article className="study-article" onMouseUp={()=>{const value=window.getSelection()?.toString().trim();if(value)setSelection(value.slice(0,10000));}}>{article?<><div className="article-meta"><span className="badge green"><CheckCircle2 size={13}/>独立审查已通过</span><span>AI 详解 · 可追溯教材依据</span></div><div className="prose"><MathText>{article.body}</MathText></div><div className="source-list"><strong><Quote size={15}/>教材依据</strong>{article.refs.map((ref:string)=>{const f=facts.find(x=>x.id===ref);return f?<button key={ref} onClick={()=>openSource(f)}>{f.title}<ExternalLink size={13}/></button>:<span key={ref}>历史教材事实：{ref}</span>;})}</div></>:current?<><div className="article-meta"><span className={'badge '+(current.status==='VERIFIED'?'green':'amber')}>{current.status==='VERIFIED'?'教材原文 · 已核验':'教材候选 · 待核验'}</span><button className="text-button" onClick={()=>openSource(current)}>查看原文<ExternalLink size={13}/></button></div><div className="prose original"><MathText>{current.content}</MathText>{current.latex&&<MathText>{`$$${current.latex}$$`}</MathText>}</div><div className="teaching-start"><Layers size={23}/><h3>让这段教材，成为完整的一课</h3><p>{current.status==='VERIFIED'?'从为什么要学、符号与条件，到证明的每一步。生成后将经过独立审查。':'请先对照原件核验。可靠的解释，从可靠的教材事实开始。'}</p>{current.status==='VERIFIED'?<><Consent checked={consent} onChange={setConsent}/><button className="primary" disabled={!!busy||!consent} onClick={generate}>生成深度教辅<ArrowRight size={16}/></button></>:<button className="secondary" onClick={()=>{setEdit({...current,source:{...current.source},verified:true});setModal('verify');}}>对照教材核验<ArrowRight size={16}/></button>}</div>{knowledge.filter(k=>k.kp===kp&&k.status!=='PUBLISHED').map(k=><div className="review-warning" key={k.id}><AlertCircle size={16}/><div><strong>教辅待修订，尚未发布</strong><p>{k.review.issues.join('；')}</p></div></div>)}</>:<Empty icon={BookOpen} title="先建立可信的知识起点" text="打开教材原页，录入并核验相关内容。" action={()=>{setPage(1);setModal('source');}} label="查看原教材"/>}</article></div></>}
    {tab==='facts'&&<><PageHeading eyebrow="可信教材" title="理解之前，先确认依据。" text="自动识别只是候选。对照原文核验，保留每一次修订。" action={<button className="primary" onClick={()=>book?setModal('manual'):setModal('import')}><Plus size={16}/>{book?'录入教材事实':'导入教材'}</button>}/>{book?<><div className="audit-strip"><div><span>教材页数</span><strong>{audit?.pages??0}</strong></div><div><span>已处理页面</span><strong>{audit?.processedPages??0}<small> / {audit?.pages??0}</small></strong></div><div><span>已发现候选</span><strong>{facts.length}</strong></div><div><span>已核验事实</span><strong className="green-text">{verified}<small> / {facts.length}</small></strong></div></div><p className="audit-note"><HelpCircle size={14}/>{audit?.notice}</p><button className="secondary" onClick={()=>setModal('framework')}><Compass size={15}/>知识框架</button> <button className="secondary" onClick={()=>setModal('sources')}><FileText size={15}/>对照文件（{sources.length}）</button> <button className="secondary" onClick={()=>setModal('structure')}><Layers size={15}/>章节依赖与符号表</button>{book&&<div className="batch-panel"><div><strong>扫描教材批量识别</strong><p>已处理 {Object.values(batch.pages??{}).filter((x:any)=>x.status==='DONE').length} 页 · 待重试 {Object.values(batch.pages??{}).filter((x:any)=>x.status==='FAILED').length} 页{batch.active?' · 正在处理第 '+(batch.currentPage??batch.from??1)+' 页':''}。结果仍须核验。</p></div>{batch.active?<button className="secondary" onClick={()=>api(`/workspaces/${book.id}/vision-batch/cancel`,{reference:batchRef}).then(x=>setToast(x.message)).catch(e=>setError(e.message))}>当前页后暂停</button>:<button className="secondary" disabled={!!busy} onClick={()=>{setBatchFrom(batch.from??1);setBatchTo(Math.min(batch.to??3,sources.find(s=>s.id===batchRef)?.pages??book.pages));setBatchConsent(false);setModal('batch');}}><ScanEye size={16}/>选择页范围并识别</button>}</div>}{audit?.unresolved?.length>0&&<div className="review-warning"><ScanEye size={18}/><div><strong>{audit.unresolved.length} 页需要辅助识别或人工核验</strong><p>扫描页、图像与复杂公式不会被猜测补齐。</p></div><button className="text-button" onClick={()=>{setPage(audit.unresolved[0].page);setModal('source');}}>查看<ArrowRight size={14}/></button></div>}<div className="fact-table"><div className="table-head"><span>教材内容</span><span>状态</span><span>操作</span></div>{facts.map(f=><div className="fact-row" key={f.id}><div><small>{f.chapter} · {f.kind}</small><strong>{f.title}</strong><p>{f.content.slice(0,120)}</p></div><span className={'badge '+(f.status==='VERIFIED'?'green':'amber')}>{f.status==='VERIFIED'?'已核验':'待核验'}</span><div className="row-actions"><button className="text-button" onClick={()=>openSource(f)}>原文</button><button className="secondary small" onClick={()=>{setEdit({...f,source:{...f.source},verified:true});setModal('verify');}}>{f.status==='VERIFIED'?'修订':'核验'}<ChevronRight size={14}/></button></div></div>)}</div></>:<Empty icon={ShieldCheck} title="还没有导入教材" text="先导入自己的 PDF，建立独立教材空间。" action={()=>setModal('import')} label="导入 PDF"/>}</>}
    {(tab==='mistakes'||tab==='transcript')&&<><PageHeading eyebrow="个人积累" title={tab==='mistakes'?'把错误，变成下一次的进步。':'课堂里的提醒，留在教材旁。'} text={tab==='mistakes'?'保留你的解题过程，找到错误发生的位置，再用复测验证。':'原始转写独立保存，课堂补充与教材原文清晰区分。'} action={<button className="primary" disabled={!book} onClick={()=>{setRecordKind(tab==='mistakes'?'mistake':'transcript');setModal('record');}}><Plus size={16}/>{tab==='mistakes'?'记录错题':'导入转写'}</button>}/>{records.filter(r=>r.kind===(tab==='mistakes'?'mistake':'transcript')).length?records.filter(r=>r.kind===(tab==='mistakes'?'mistake':'transcript')).map(r=><div className="record-item" key={r.id}><div className="record-date">{new Date(r.created).toLocaleDateString('zh-CN')}</div><h3>{r.raw.title??r.raw.question?.slice(0,60)??'课堂转写'}</h3><span className="badge">{r.raw.dimension??'课堂补充'}</span><div className="prose"><MathText>{r.kind==='transcript'?(r.raw.text??''):(r.raw.question??'')}</MathText></div>{r.raw.steps&&<p><strong>我的过程：</strong>{r.raw.steps}</p>}{r.raw.rootCause&&<p><strong>错误根因：</strong>{r.raw.rootCause}</p>}{records.filter(d=>d.kind==='reflection'&&d.raw.sourceRecord===r.id).map(d=><div className="personal-summary" key={d.id}><span className="badge">{r.kind==='transcript'?'课堂补充':'个人易错'} · AI 整理</span><p>{d.derived.summary}</p>{d.derived.claims?.map((c:any,i:number)=><div key={i}><span className={'badge '+(c.needsVerify?'amber':'')}>{c.needsVerify?'待核验':c.identity}</span><div className="prose"><MathText>{c.text}</MathText></div></div>)}</div>)}<div className="record-actions"><span>原始记录已保存</span><button className="text-button" disabled={!!busy} onClick={()=>{if(window.confirm('将这条原始学习记录和相关已核验教材发送给配置的模型，整理结果独立保存，是否继续？'))action('整理个人学习记录',async()=>{await poll((await api(`/workspaces/${book.id}/records/${r.id}/analyze`,{consent:true})).task);await load();setToast('整理结果已独立保存，原始记录未改变。');});}}>AI 整理<Layers size={14}/></button>{r.kind==='mistake'&&<button className="text-button" onClick={()=>{setRecordKind('evidence');setModal('record');}}>添加复测证据<ArrowRight size={14}/></button>}</div></div>):<Empty icon={tab==='mistakes'?Bookmark:NotebookPen} title={tab==='mistakes'?'每道错题，都可以成为线索':'留住课堂中的关键解释'} text={tab==='mistakes'?'记录原题、步骤与根因，学习诊断才有可靠依据。':'支持粘贴或导入 Word（.docx）和 TXT 笔记。原文件保留，录音转写服务后续接入。'}/>}</>}
    {tab==='exercise'&&<><PageHeading eyebrow="有依据的训练" title="练习不是刷数量，而是补上缺口。" text="围绕已核验教材与个人弱点出题，经过独立 Solver 和 Critic 审查后才能用于训练。"/>{book?<><label className="exercise-select">当前训练知识点<select value={kp} onChange={e=>setKp(e.target.value)}>{facts.filter(f=>f.status==='VERIFIED').map(f=><option key={f.id} value={f.kp}>{f.title}</option>)}</select></label><Consent checked={consent} onChange={setConsent}/><button className="primary" disabled={!!busy||!consent||!facts.some(f=>f.kp===kp&&f.status==='VERIFIED')} onClick={()=>action('原创出题与独立验题',async()=>{const r=await poll((await api(`/workspaces/${book.id}/questions`,{kp,consent})).task);await load();setToast(r.status==='PUBLISHED'?'练习已通过独立验题。':'题目未通过验题，未发布。');})}><Plus size={16}/>生成针对性练习</button>{questions.map(q=><div className="record-item" key={q.id}>{q.status==='PUBLISHED'?<><span className="badge green">独立验题已通过 · {q.payload.difficulty}</span><div className="prose"><MathText>{q.payload.question}</MathText></div><details><summary>完成后查看答案与解题理由</summary><div className="prose"><MathText>{q.payload.solution.answer+'\n\n'+q.payload.solution.steps}</MathText></div></details><button className="text-button" onClick={()=>{setRecordKind('evidence');setModal('record');}}>记录这次训练的证据<ArrowRight size={14}/></button></>:<div className="review-warning"><AlertCircle size={16}/><div><strong>题目待核验，未用于训练</strong><p>{q.review.issues.join('；')}</p></div></div>}</div>)}{facts.filter(f=>f.status==='VERIFIED'&&f.kind==='习题').map(f=><div className="record-item" key={f.id}><span className="badge">教材原题 · 已核验</span><h3>{f.title}</h3><div className="prose"><MathText>{f.content}</MathText></div><button className="text-button" onClick={()=>openSource(f)}>查看教材依据<ExternalLink size={13}/></button></div>)}</>:<Empty icon={Layers} title="先建立可信教材范围" text="核验相关知识点后，再生成并验证练习。"/>}</>}
    {tab==='diagnosis'&&<><PageHeading eyebrow="学习画像" title="知道卡在哪里，才知道往哪走。" text="依据错题与复测记录评估；证据不足时保持待评估。" action={<button className="secondary" disabled={!book} onClick={()=>{setRecordKind('evidence');setModal('record');}}><Plus size={16}/>添加学习证据</button>}/><div className="diagnosis-list">{diagnosis.map(d=><div className="diagnosis-row" key={d.dimension}><div className="dimension-icon"><Target size={19}/></div><div><h3>{d.dimension}</h3><span className={d.status==='待评估'?'muted':'green-text'}>{d.status} · {d.evidence.length} 条证据</span>{d.plan&&<p>基础训练 {d.plan.count} 题 · {d.plan.type} · {d.plan.retestHours} 小时后复测<br/>{d.plan.passCriteria}</p>}{d.evidence.map((e:any)=><details key={e.id}><summary>查看证据：{e.raw.title??e.raw.question?.slice(0,45)??e.raw.notes??'复测记录'}</summary><p>{e.raw.rootCause??e.raw.notes??e.raw.steps}</p></details>)}</div><span className={'badge '+(d.evidence.length?'green':'')}>{d.evidence.length?'有证据':'待评估'}</span></div>)}</div>{!book&&<Empty icon={Target} title="诊断需要真实学习证据" text="导入教材后，记录错题和复测，逐步建立学习画像。"/>}</>}
    {tab==='review'&&<><PageHeading eyebrow="正式产品路线" title="让一学期的积累，成为你的复习资料。" text="期末资料与 Word/PDF 高质量导出将在后续版本完成；当前不会生成未经验证的占位文件。"/><div className="roadmap"><div><Calendar size={28}/><h3>你的期末复习工作台</h3><p>完整个人教辅 · 公式与定理条件速查 · 弱点本<br/>代表性错题 · 题型地图 · 专项训练<br/>7 天 / 3 天 / 1 天复习计划</p><span className="badge amber">规划中 · 尚未实现</span></div></div></>}
    {tab==='settings'&&<><PageHeading eyebrow="工作台设置" title="数据在本机，学习由你掌握。" text="配置教学模型、管理备份，并查看软件的维护与更新状态。"/><div className="settings-section"><div className="settings-description"><MessageCircle size={22}/><h3>教学与视觉模型</h3><p>只发送当前任务需要的相关片段。密钥仅在本次运行中保留。</p></div><div className="settings-form"><SettingsFields settings={settings} setSettings={setSettings}/><button className="primary" disabled={!!busy} onClick={()=>action('保存设置',async()=>{setSettings({...await api('/settings',settings),apiKey:''});setToast('设置已保存，密钥仅保存在服务内存。');})}><Check size={16}/>保存设置</button></div></div><div className="settings-section"><div className="settings-description"><Database size={22}/><h3>本地数据与备份</h3><p>备份包含教材与学习记录。恢复前再次保存当前数据。</p></div><div className="settings-form"><button className="secondary" disabled={!!busy} onClick={()=>action('备份资料',async()=>{const result=await api('/backups',{});setToast(result.message);setBackups(await api('/backups'));})}><Download size={16}/>创建完整备份</button><button className="text-button" onClick={()=>api('/backups').then(setBackups)}>查看备份</button>{backups.map(b=><div className="backup-row" key={b}><FileText size={15}/>{b}</div>)}<p className="muted">恢复时关闭软件，运行“恢复学习数据.bat”，选择备份名称。原始资料不会静默覆盖。</p></div></div><div className="settings-section"><div className="settings-description"><RefreshCw size={22}/><h3>维护与在线更新</h3><p>当前版本 {version} · 先备份，后更新；失败恢复稳定版本。</p></div><div className="settings-form"><button className="secondary" onClick={()=>action('检查在线更新',async()=>{setUpdates(await api('/updates/check',{}));setModal('inbox');setInbox(await api('/inbox'));})}><RefreshCw size={16}/>检查更新</button><button className="secondary" onClick={()=>action('运行维护检查',async()=>{await api('/maintenance',{});setToast('检查完成，可在消息箱查看报告。');})}><ShieldCheck size={16}/>立即检查</button><p className="muted">后台定时维护需运行“注册长期维护.bat”。检查不依赖聊天窗口；AI 修复能力及真实验证状态见维护报告。</p></div></div></>}
    </>}
    </main>
    {book&&tab==='learn'&&<><button className="mobile-tutor primary" onClick={()=>setTutorOpen(!tutorOpen)}><MessageCircle size={17}/>{tutorOpen?'返回教材':'打开 Tutor'}</button><aside className={'tutor '+(tutorOpen?'mobile-open':'')}><div className="tutor-heading"><span className="tutor-mark"><Compass size={20}/></span><div><strong>学习 Tutor</strong><small>围绕你的教材，陪你往深处走</small></div><span className="status-dot"/></div><div className="tutor-context"><Layers size={14}/><span>{current?.title??'请先选择知识点'}</span></div><div className="chat-list">{!messages.length?<div className="tutor-welcome"><span className="tutor-symbol">∂</span><h3>哪里还没懂？</h3><p>选中教材中的一句话或公式，<br/>我们一起把它拆开看。</p><div className="suggestions">{['这个定义为什么这样写？','这个条件可以去掉吗？','证明的这一步为什么成立？'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}<ArrowUp size={13}/></button>)}</div></div>:messages.map(m=><div key={m.id} className={'chat-message '+m.role}>{m.role==='assistant'&&<span className="chat-label">知微 Tutor</span>}{m.status==='NEEDS_REVISION'?<p className="muted">此回答未通过审查，暂未发布。</p>:<div className="prose"><MathText>{m.body}</MathText></div>}</div>)}{busy&&<div className="chat-thinking"><Loader2 size={14} className="spin"/>正在处理与检查</div>}<div ref={chatBottom}/></div><div className="chat-compose">{selection&&<div className="selected-text"><Quote size={13}/><span>{selection}</span><button className="icon-button" aria-label="清除选中内容" onClick={()=>setSelection('')}><X size={13}/></button></div>}<Consent checked={consent} onChange={setConsent}/><div className="chat-input"><textarea aria-label="向 Tutor 提问" placeholder="告诉我，具体卡在哪一步…" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();ask();}}}/><div><span>Ctrl ↵ 发送</span><button className="send-button" aria-label="发送问题" disabled={!question.trim()||!!busy||!consent} onClick={ask}><ArrowUp size={18}/></button></div></div><p>AI 内容经审查仍可能有误，请结合教材核验。</p></div></aside></>}
   </div>
  </div>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
  <input ref={file} type="file" accept="application/pdf,.pdf" hidden onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);e.target.value='';}}/>
  <Modal open={modal==='import'} onClose={()=>setModal('')} title="导入你的教材" description="每本教材建立独立学习空间，原 PDF 保存在本机。"><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])importFile(e.dataTransfer.files[0]);}}><Upload size={32}/><h3>拖入 PDF，或点击选择</h3><p>支持文字型与扫描教材 · 最大 150 MB</p><button className="primary" disabled={!!busy} onClick={()=>file.current?.click()}>选择 PDF 文件</button></div><div className="modal-tip"><ShieldCheck size={16}/>识别结果先进入候选层；扫描与复杂公式可使用视觉辅助，需确认后成为可信事实。</div></Modal>
  <Modal open={modal==='batch'} onClose={()=>setModal('')} title="按章节批量视觉识别" description="选择同本书的来源和范围。建议先选 1–3 页试识别；页面逐页发送给你配置的 Vision Model，按服务用量计费。"><label className="source-select">识别来源<select value={batchRef} onChange={e=>{setBatchRef(e.target.value);setBatchFrom(1);setBatchTo(3);}}>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><div className="field-grid"><label>起始页<input type="number" min={1} max={sources.find(s=>s.id===batchRef)?.pages??book?.pages??1} value={batchFrom} onChange={e=>setBatchFrom(Number(e.target.value))}/></label><label>结束页<input type="number" min={batchFrom} max={sources.find(s=>s.id===batchRef)?.pages??book?.pages??1} value={batchTo} onChange={e=>setBatchTo(Number(e.target.value))}/></label></div><p className="muted">已完成的页自动跳过，失败或中断的页可以续做。关闭浏览器后任务仍在本机运行；关闭服务会中断，重新选择原范围即可继续。识别完成不等于内容准确或已核验。</p><label className="consent"><input type="checkbox" checked={batchConsent} onChange={e=>setBatchConsent(e.target.checked)}/><span>同意将所选页面图像发送给配置的视觉服务，并承担该服务的用量费用</span></label><button className="primary full" disabled={!!busy||!batchConsent||!Number.isInteger(batchFrom)||!Number.isInteger(batchTo)||batchFrom<1||batchTo<batchFrom||batchTo>(sources.find(s=>s.id===batchRef)?.pages??book?.pages??0)} onClick={()=>action('批量视觉识别',async()=>{const job=await api(`/workspaces/${book.id}/vision-batch`,{from:batchFrom,to:batchTo,reference:batchRef,consent:true});setModal('');const result=await poll(job.task);setBatch(await api(`/workspaces/${book.id}/vision-batch?reference=${encodeURIComponent(batchRef)}`));await load();setToast(`批量识别${result.status==='DONE'?'完成':result.status==='PAUSED'?'已暂停':'部分完成'}：新完成 ${result.completed} 页，跳过 ${result.skipped} 页，失败 ${result.failed} 页。候选仍待核验。`);})}><ScanEye size={16}/>开始或继续识别</button></Modal>
  <Modal open={modal==='books'} onClose={()=>setModal('')} title="你的教材空间" description="不同教材的知识体系与学习记录独立保存。"><div className="book-list">{books.map(b=><button key={b.id} onClick={()=>{setBook(b);setModal('');setPage(1);setKp('');}}><span className="book-cover"><BookOpen size={22}/></span><div><strong>{b.title}</strong><small>{b.pages} 页 · {new Date(b.created).toLocaleDateString('zh-CN')}</small></div>{book?.id===b.id?<Check size={18}/>:<ChevronRight size={18}/>}</button>)}</div><button className="primary full" onClick={()=>setModal('import')}><Plus size={16}/>导入另一份教材</button></Modal>
  <Modal open={modal==='search'} onClose={()=>setModal('')} title="搜索教材知识" description="检索当前教材的标题、章节和原文内容。"><div className="search-field"><Search size={19}/><input autoFocus placeholder="输入概念、定理或关键词" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="search-results">{facts.filter(f=>search&&[f.title,f.chapter,f.content].some(s=>s.includes(search))).slice(0,30).map(f=><button key={f.id} onClick={()=>{setKp(f.kp);setTab('learn');setModal('');}}><div><small>{f.chapter}</small><strong>{f.title}</strong></div><ArrowRight size={16}/></button>)}{!search&&<p className="muted">输入关键词，找到相关知识点。</p>}</div></Modal>
  <Modal open={modal==='source'} onClose={()=>setModal('')} title="教材原件" description="显示内部 PDF 页索引，不等同于教材印刷页码。">{book&&<><label className="source-select">对照来源<select value={sourceRef} onChange={e=>{setSourceRef(e.target.value);setPage(1);}}>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><PDFPage reference={sourceRef} workspace={book.id} page={page} setPage={setPage} pages={sources.find(s=>s.id===sourceRef)?.pages??book.pages} onVision={image=>{if(!window.confirm('将本页教材图像和该页提取文字发送给配置的视觉服务，识别结果仍需核验。是否继续？'))return;action('视觉识别',async()=>{await poll((await api(`/workspaces/${book.id}/vision`,{page,image,reference:sourceRef,consent:true})).task);await load();setToast('视觉候选已保存，请对照原件核验。');});}}/></>}</Modal>
  <Modal open={modal==='verify'||modal==='manual'} onClose={()=>{setModal('');setEdit(null);}} title={modal==='manual'?'录入教材事实':'对照原文核验'} description="请核对定义、全部条件、符号与公式。保存会建立新版本，不改写历史。"><FactForm key={edit?.id??modal} value={edit} book={book} onSource={()=>edit&&openSource(edit)} onSave={value=>action('保存教材事实',async()=>{await api(`/workspaces/${book.id}/facts${edit?'/'+edit.id+'/verify':''}`,value);await load();setModal('');setEdit(null);setToast('事实版本已保存。');})}/></Modal>
  <Modal open={modal==='record'} onClose={()=>setModal('')} title={recordKind==='transcript'?'导入课堂转写':recordKind==='evidence'?'记录复测证据':'记录一道错题'} description="原始记录独立保存；每条记录可以关联教材知识点。"><RecordForm workspace={book?.id??''} kind={recordKind} facts={facts} kp={kp} onSave={value=>action('保存学习记录',async()=>{await api(`/workspaces/${book.id}/records`,value);await load();setModal('');setToast('学习记录已保存。');})}/></Modal>
  <input ref={referenceFile} type="file" accept="application/pdf,.pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(f&&book)action('添加同书对照资料',async()=>{const form=new FormData();form.append('pdf',f);form.append('title',f.name.replace(/\.pdf$/i,''));await api(`/workspaces/${book.id}/references`,form);setSources(await api(`/workspaces/${book.id}/sources`));setToast('对照原件已保存在当前教材空间。');});e.target.value='';}}/>
  <Modal open={modal==='sources'} onClose={()=>setModal('')} title="同一本书，多个对照来源" description="文字版用于提取内容，高清扫描版用于检查公式和图形。各文件原样保存，不自动宣称内容一致。"><div className="book-list">{sources.map(s=><button key={s.id} onClick={()=>{setSourceRef(s.id);setPage(1);setModal('source');}}><FileText size={20}/><div><strong>{s.title}</strong><small>{s.kind==='primary'?'主要提取来源':'原件对照资料'}</small></div><ChevronRight size={16}/></button>)}</div><button className="secondary full" disabled={!!busy} onClick={()=>referenceFile.current?.click()}>添加同本书的对照 PDF</button></Modal>
  <Modal open={modal==='activity'} onClose={()=>setModal('')} title="任务动态" description="查看工作台正在做什么。任务记录保存在本机，关闭页面后仍可查看完成或失败结果。"><div className="activity-summary"><ShieldCheck size={20}/><div><strong>{activityOnline?'本机学习服务已连接':'正在等待服务恢复'}</strong><p>{activity.filter(t=>['RUNNING','QUEUED'].includes(t.status)).length} 个任务处理中 · {activity.filter(t=>t.status==='DONE').length} 个已完成 · {activity.filter(t=>t.status==='FAILED').length} 个失败（最近50条）</p></div></div>{activity.map(t=><div className="activity-row" key={t.id}><div className="activity-row-heading"><strong>{taskNames[t.kind]??t.kind}</strong><span className={'badge '+(t.status==='FAILED'?'amber':'green')}>{({RUNNING:'处理中',QUEUED:'排队中',DONE:'已完成',FAILED:'失败，待处理'} as Record<string,string>)[t.status]??t.status}</span></div><small>{t.textbook??'软件任务'} · {new Date(t.created).toLocaleString('zh-CN')}</small>{['RUNNING','QUEUED'].includes(t.status)&&<><progress max={100} value={t.progress} aria-label="任务进度"/><p>{t.progress}% · 最后更新 {new Date(t.updated).toLocaleTimeString('zh-CN')}。等待模型响应时进度可能暂时不变。</p></>}{t.error&&<p className="error">{t.error}</p>}</div>)}{!activity.length&&<p className="muted">还没有任务。导入教材或开始识别后，进度和结果会显示在这里。</p>}<button className="secondary full" onClick={()=>openInbox().catch(e=>setError(e.message))}><Bell size={16}/>查看维护报告与更新</button><button className="secondary full" disabled={!!busy} onClick={()=>action('注册长期维护',async()=>{await poll((await api('/maintenance/register',{confirm:true})).task);setToast('已启用每日20:00与每周六10:00维护，报告在消息箱查看。');})}><Calendar size={16}/>启用每日与每周维护</button><p className="muted">此按钮会添加当前用户的Windows任务计划。关机时暂停，登录后补跑；检查结果可在消息箱查看。</p></Modal>
  <Modal open={modal==='framework'} onClose={()=>setModal('')} title="教材知识框架" description="直接按纯文字PDF的原书顺序展开：章、节、知识点、定义、定理、证明与例题。正文来自教材原文。">{framework?.chapters?.length>0&&<p className="framework-path">{framework.chapters.length} 章 · {framework.chapters.reduce((n:number,c:any)=>n+c.sections.length,0)} 节 · {framework.chapters.reduce((n:number,c:any)=>n+c.sections.reduce((m:number,s:any)=>m+s.topics.length,0),0)} 个知识点 · {framework.coverage?.entries??0} 条教材正文。点击目录展开，继续点击条目阅读原文。</p>}{framework?.introduction&&<details className="framework-section"><summary>引言与教材整理说明</summary><FrameworkContents entries={framework.introduction.entries}/></details>}{framework?.chapters?.map((c:any)=><div className="framework-chapter" key={c.number}><span className="badge green">纯文字教材原文</span><h3>第 {c.number} 章 · {c.title}</h3><FrameworkContents entries={c.entries??[]}/>{c.sections.map((section:any)=><details className="framework-section" key={section.number}><summary>{section.number} {section.title}</summary><FrameworkContents entries={section.entries??[]}/>{section.topics.map((topic:any)=><details className="framework-topic" key={topic.number}><summary><MathText>{topic.number+' '+topic.title}</MathText></summary><FrameworkContents entries={topic.entries??[]}/></details>)}</details>)}</div>)}{!framework?.chapters?.length&&<p className="muted">还没有可提取的文字目录。请导入带正文文字的教材PDF；扫描原件保留作为对照资料。</p>}<p className="muted">{framework?.notice}</p><button className="secondary full" disabled={!!busy} onClick={()=>action('从教材原文更新目录',async()=>{await poll((await api(`/workspaces/${book.id}/framework`,{})).task);setFramework(await api(`/workspaces/${book.id}/framework`));setToast('已按纯文字教材更新详细框架，原文保留，全程本机处理。');})}><RefreshCw size={15}/>重新从教材原文提取目录（本机处理）</button></Modal>
  <Modal open={modal==='structure'} onClose={()=>setModal('')} title="教材知识结构" description="依赖与符号按章节分别保存。自动整理的关系仍需对照教材确认。"><Consent checked={consent} onChange={setConsent}/><button className="primary" disabled={!consent||!!busy} onClick={()=>action('全书结构分析',async()=>{await poll((await api(`/workspaces/${book.id}/structure`,{consent})).task);await load();setToast('结构候选已保存，请核验依赖与符号。');})}><Layers size={16}/>整理全书结构候选</button><h3>知识依赖</h3>{structure.edges.map((e:any,i:number)=><div className="structure-row" key={i}><p>{facts.find(f=>f.kp===e.from_kp)?.title??e.from_kp} → {facts.find(f=>f.kp===e.to_kp)?.title??e.to_kp}<small> · {e.kind}</small></p><button className="secondary small" disabled={e.status==='VERIFIED'} onClick={()=>action('核验依赖',async()=>{await api(`/workspaces/${book.id}/structure/verify`,{kind:'edge',from:e.from_kp,to:e.to_kp,relation:e.kind});await load();})}>{e.status==='VERIFIED'?'已核验':'确认关系'}</button></div>)}<h3>章节符号</h3>{structure.symbols.map((sym:any,i:number)=><div className="structure-row" key={i}><p>{sym.chapter} · {sym.symbol}：{sym.meaning}</p><button className="secondary small" disabled={sym.status==='VERIFIED'} onClick={()=>action('核验符号',async()=>{await api(`/workspaces/${book.id}/structure/verify`,{kind:'symbol',chapter:sym.chapter,symbol:sym.symbol});await load();})}>{sym.status==='VERIFIED'?'已核验':'确认含义'}</button></div>)}{!structure.edges.length&&!structure.symbols.length&&<p className="muted">尚无结构候选。先分析全书，再逐项确认；不会自动合并不同章节中同名符号。</p>}</Modal>
  <Modal open={modal==='inbox'} onClose={()=>setModal('')} title="消息与更新" description="查看维护报告、版本变更及更新风险。">{updates&&<div className="update-card"><span className="badge green">当前 {updates.current}</span><h3>{updates.manifest?'发现版本 '+updates.manifest.version:'更新状态'}</h3><p>{updates.message??(updates.status==='CURRENT'?'当前已经是最新版本。':'更新已通过签名验证。')}</p>{updates.manifest&&<><p>{updates.manifest.changes.join('；')}</p><p>风险：{updates.manifest.risk}<br/>数据库：{updates.manifest.databaseImpact}</p><details><summary>测试摘要</summary>{updates.manifest.tests.map((t:string)=><p key={t}>{t}</p>)}</details></>}{updates.status==='AVAILABLE'&&<button className="primary" onClick={()=>action('下载更新',async()=>{await poll((await api('/updates/download',{})).task);setUpdates({...updates,status:'DOWNLOADED'});})}><Download size={16}/>{updates.manifest?.delivery==='full'?'下载完整更新':'下载补丁'}</button>}{updates.status==='DOWNLOADED'&&<button className="primary" onClick={()=>{if(window.confirm('更新将自动备份数据、停止软件并安装。失败将回滚。是否立即更新？'))action('安装并重启',async()=>{await api('/updates/install',{confirm:true});setToast('正在安装，软件将重新启动。');});}}>立即更新并重启</button>}{updates.manifest&&<button className="text-button" onClick={()=>api('/updates/remind',{}).then(()=>setToast('已记录稍后提醒。'))}>稍后提醒</button>}</div>}<button className="secondary full" onClick={()=>action('检查更新',async()=>setUpdates(await api('/updates/check',{})))}><RefreshCw size={15}/>检查在线更新</button><div className="inbox-list">{inbox.map(n=><div key={n.id}><small>{new Date(n.created).toLocaleString('zh-CN')}</small><h3>{n.title}</h3>{n.kind==='reminder'&&n.body.next&&<p>{Date.now()>=Date.parse(n.body.next)?'更新提醒已到期，请检查并安装可用更新。':'下次更新提醒：'+new Date(n.body.next).toLocaleString('zh-CN')}</p>}<details><summary>查看详情</summary><pre>{JSON.stringify(n.body,null,2)}</pre></details></div>)}{!inbox.length&&<p className="muted">暂时没有新消息。维护与更新报告会出现在这里。</p>}</div></Modal>
 </div>;
}
function Consent({checked,onChange}:{checked:boolean,onChange:(v:boolean)=>void}){return <label className="consent"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>允许发送相关教材片段、卡点及学习记录给配置的 AI 服务</span></label>;}
function Empty({icon:Icon,title,text,action,label}:{icon:any,title:string,text:string,action?:()=>void,label?:string}){return <div className="empty"><Icon size={32}/><h3>{title}</h3><p>{text}</p>{action&&<button className="secondary" onClick={action}>{label}<ArrowRight size={15}/></button>}</div>;}
function PageHeading({eyebrow,title,text,action}:{eyebrow:string,title:string,text:string,action?:React.ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>;}
function SettingsFields({settings:s,setSettings:set}:{settings:any,setSettings:(v:any)=>void}){return <><div className="field-grid"><label>Provider<input value={s.provider} onChange={e=>set({...s,provider:e.target.value})}/></label><label>Base URL<input value={s.baseUrl} onChange={e=>set({...s,baseUrl:e.target.value})}/></label><label>Text Model<input placeholder="填写官方支持的文本模型" value={s.textModel} onChange={e=>set({...s,textModel:e.target.value})}/></label><label>Vision Model<input placeholder="填写支持图片输入的模型" value={s.visionModel} onChange={e=>set({...s,visionModel:e.target.value})}/></label><label className="span-two">API Key<input type="password" autoComplete="off" placeholder={s.hasKey?'已有本次运行密钥；保存时请重新输入':'仅保存在服务内存，重启后重新输入'} value={s.apiKey} onChange={e=>set({...s,apiKey:e.target.value})}/></label><label>超时（秒）<input type="number" min={5} max={300} value={s.timeout/1000} onChange={e=>set({...s,timeout:Number(e.target.value)*1000})}/></label><label>重试次数<input type="number" min={0} max={3} value={s.retries} onChange={e=>set({...s,retries:Number(e.target.value)})}/></label></div></>;}
function FactForm({value,book,onSave,onSource}:{value:any,book:any,onSave:(v:any)=>void,onSource:()=>void}){const [f,set]=useState(value??{chapter:'待整理',kind:'定义',title:'',content:'',latex:'',source:{quote:'',pdfIndex:1},verified:false});return <form onSubmit={e=>{e.preventDefault();onSave({chapter:f.chapter,kind:f.kind,title:f.title,content:f.content,latex:f.latex,source:{...f.source,quote:f.source.quote||f.content},verified:f.verified});}}><div className="field-grid"><label>章节<input required value={f.chapter} onChange={e=>set({...f,chapter:e.target.value})}/></label><label>类型<select value={f.kind} onChange={e=>set({...f,kind:e.target.value})}>{['定义','定理','推论','公式','证明','例题','习题','片段'].map(k=><option key={k}>{k}</option>)}</select></label><label className="span-two">标题<input required value={f.title} onChange={e=>set({...f,title:e.target.value})}/></label><label className="span-two">教材内容<textarea required rows={7} value={f.content} onChange={e=>set({...f,content:e.target.value})}/></label><label className="span-two">公式（LaTeX，可选）<textarea rows={2} value={f.latex} onChange={e=>set({...f,latex:e.target.value})}/></label><label>PDF 内部页索引<input type="number" min={1} max={book?.pages??1} value={f.source.pdfIndex??''} onChange={e=>set({...f,source:{...f.source,pdfIndex:e.target.value?Number(e.target.value):undefined}})}/></label><label>原文锚点<input value={f.source.quote} onChange={e=>set({...f,source:{...f.source,quote:e.target.value}})}/></label></div>{f.latex&&<div className="formula-preview"><MathText>{`$$${f.latex}$$`}</MathText></div>}<label className="consent"><input type="checkbox" checked={f.verified} onChange={e=>set({...f,verified:e.target.checked})}/><span>我已对照原件确认内容、条件、符号及公式准确</span></label><div className="modal-actions">{value&&<button type="button" className="secondary" onClick={onSource}>查看原页</button>}<button className="primary" type="submit"><Check size={16}/>{f.verified?'保存已核验版本':'保存待核验候选'}</button></div></form>;}
function RecordForm({workspace,kind,facts,kp,onSave}:{workspace:string,kind:string,facts:any[],kp:string,onSave:(v:any)=>void}){const [r,set]=useState<any>({title:'',question:'',steps:'',rootCause:'',text:'',dimension:'概念',outcome:'needs_review',notes:''});const [selected,setSelected]=useState(kp);return <form onSubmit={e=>{e.preventDefault();onSave({kind,kp:selected,raw:r,derived:{}});}}><div className="field-grid"><label className="span-two">关联知识点<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">暂不关联</option>{facts.map(f=><option key={f.id} value={f.kp}>{f.title}</option>)}</select></label><label className="span-two">标题<input required value={r.title} onChange={e=>set({...r,title:e.target.value})}/></label>{kind==='transcript'?<><label className="span-two">课堂转写<textarea required rows={10} value={r.text} onChange={e=>set({...r,text:e.target.value})}/></label><label className="span-two">或导入 Word / TXT<input type="file" accept=".docx,.txt,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;set({...r,importing:true,importError:''});try{const form=new FormData();form.append('notes',file);const data=await api(`/workspaces/${workspace}/notes-file`,form);set({...r,text:data.text,title:r.title||file.name,source:data.source,warnings:data.warnings,importing:false});}catch(error){set({...r,importing:false,importError:(error as Error).message});}e.target.value='';}}/>{r.importing&&<small>正在提取笔记文字…</small>}{r.source&&<small>原文件已保留：{r.source.name}。保存前请检查提取文字。</small>}{r.warnings?.map((warning:string)=><small className="error" key={warning}>{warning}</small>)}{r.importError&&<small className="error">{r.importError}</small>}</label></>:<><label>评估维度<select value={r.dimension} onChange={e=>set({...r,dimension:e.target.value})}>{['概念','符号/定义','定理条件','计算','方法选择','证明/推理','综合应用','稳定性','长期保持'].map(d=><option key={d}>{d}</option>)}</select></label><label>结果<select value={r.outcome} onChange={e=>set({...r,outcome:e.target.value})}><option value="needs_review">需要复习</option><option value="pass">已独立通过</option></select></label><label className="span-two">原题或复测任务<textarea required rows={4} value={r.question} onChange={e=>set({...r,question:e.target.value})}/></label><label className="span-two">我的步骤与错误位置<textarea rows={3} value={r.steps} onChange={e=>set({...r,steps:e.target.value})}/></label><label className="span-two">根因 / 正确方法 / 复测证据<textarea required rows={3} value={r.rootCause} onChange={e=>set({...r,rootCause:e.target.value})}/></label></>}</div><div className="modal-actions"><button type="submit" disabled={!!r.importing} className="primary"><Check size={16}/>保存原始记录</button></div></form>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
