import React,{useEffect,useState} from 'react';
import {BookOpen,MessageCircle,RefreshCw,Search,ShieldCheck,Pause,ArrowRight} from 'lucide-react';

export default function StudyWorkbench({workspace,api,action,poll,renderText,onAsk,onSource,busy}:{workspace:string;api:(u:string,b?:any)=>Promise<any>;action:(label:string,fn:()=>Promise<void>)=>Promise<void>;poll:(task:string)=>Promise<any>;renderText:(text:string)=>React.ReactNode;onAsk:(unit:any,text?:string)=>void;onSource:(page:number)=>void;busy:string}){
 const [data,setData]=useState<any>({units:[]});const [unit,setUnit]=useState('');const [search,setSearch]=useState('');const [consent,setConsent]=useState(false);const [online,setOnline]=useState(true);
 const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');
 const prefix=`/workspaces/${workspace}/study`;
 async function refresh(){try{const result=await api(prefix);setData(result);setLoadError('');setUnit(old=>result.units.some((u:any)=>u.id===old)?old:result.units[0]?.id||'');}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let gone=false;let timer:ReturnType<typeof setTimeout>;setData({units:[]});setUnit('');setLoading(true);setLoadError('');async function update(){try{const result=await api(prefix);if(!gone){setData(result);setLoadError('');setUnit(old=>result.units.some((u:any)=>u.id===(old||localStorage.getItem('study-unit:'+workspace)))?(old||localStorage.getItem('study-unit:'+workspace)||''):result.units[0]?.id||'');}}catch(e){if(!gone)setLoadError((e as Error).message);}finally{if(!gone){setLoading(false);timer=setTimeout(update,3000);}}}void update();return()=>{gone=true;clearTimeout(timer);};},[workspace]);
 const current=data.units.find((u:any)=>u.id===unit)??data.units[0];const lesson=current?.lesson;const visible=data.units.filter((u:any)=>!search||(u.number+' '+u.title+' '+u.chapter).includes(search));const chapters=[...new Set(visible.map((u:any)=>u.chapter))] as string[];
 const focusNames:Record<string,string>={concept:'概念',definition:'严格定义',symbol:'符号含义',condition:'条件与边界',formula:'公式',property:'性质',theorem:'定理',proof_goal:'证明目标',proof_strategy:'证明策略',proof_step:'证明步骤',hidden_step:'隐藏步骤',example:'例题',method:'解题方法',exercise:'练习',diagram:'图像',remark:'注释',connection:'知识联系'};
 const choose=(u:any)=>{setUnit(u.id);localStorage.setItem('study-unit:'+workspace,u.id);};
 if(loading)return <section className="lesson-empty" role="status"><RefreshCw size={30}/><h2>正在读取整本教材知识框架</h2><p>首次整理会检查全文、公式与来源；完成后显示实际构建进度。</p></section>;
 if(loadError&&!data.units.length)return <section className="lesson-empty" role="alert"><h2>教材框架暂时无法读取</h2><p>{loadError}</p><button className="primary" onClick={()=>{setLoading(true);void refresh();}}>重新读取</button></section>;
 return <div className="review-workbench"><div className="study-heading"><div><div className="eyebrow">整本教材 · 知识与教学</div><h1>教材知识点复习</h1><p className="muted">按章节学习，解释符号、条件和每一步推导。原文保留为对照资料。</p></div><button className="primary" disabled={!current} onClick={()=>onAsk(current)}><MessageCircle size={16}/>AI 问答</button></div>
 <div className="knowledge-build-summary" aria-label="整本教材构建进度"><div><span>教材知识层</span><strong>{data.build?.coverage?.accepted??0}</strong><small>个原文块自动纳入</small></div><div><span>局部识别异常</span><strong>{data.build?.coverage?.localExceptions??0}</strong><small>个原文块需要核对</small></div><div><span>深度教学节点</span><strong>{data.build?.teachingCoverage?.teachingNodes??0}</strong><small>个节点独立审核通过</small></div><div><span>全书教学进度</span><strong>{data.completed??0} / {data.total??0}</strong><small>部分，不以全文提取代替教学完成</small></div></div><p className="conversion-status" role="status" aria-live="polite" aria-atomic="true">全文转换：{data.conversion?.pages??0} 页，{data.conversion?.capturedLines??0} / {data.conversion?.textLines??0} 行，{data.conversion?.entries??0} 个原文条目；{data.conversion?.complete?'行覆盖完整':'仍有遗漏待处理'}。AI 逐条审核：{data.completed??0} / {data.total??data.units.length} 部分。</p>{loadError&&<div className="study-load-error" role="alert"><p>进度暂时无法更新：{loadError}。当前显示最近读取的内容。</p><button className="secondary" onClick={()=>void refresh()}>重试更新</button></div>}<div className="study-pipeline"><div><strong role="status" aria-live="polite">{data.active?'正在自动整理：'+(data.current??'识别教材'):'全文解析 → 教材知识层 → 教学粒度拆分 → 独立审核'}</strong><p>当前阶段：{data.build?.phase??'全文解析'}。{data.completed??0} / {data.total??data.units.length} 节已整理。扫描页调用视觉模型；文字页直接解析。{data.recognitionMissing>0?` 尚有 ${data.recognitionMissing} 页识别未完成。`:null}</p>{data.lastError&&<p className="error" role="alert">{data.lastError}</p>}</div><div className="pipeline-controls"><label className="consent"><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/>联网查书目信息和概念资料</label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意发送教材片段给模型，承担识别与整理费用</label>{data.active?<button className="secondary" disabled={!!busy} onClick={()=>action('暂停自动整理',async()=>{await api(prefix+'/pause',{});await refresh();})}><Pause size={15}/>当前步骤后暂停</button>:<button className="secondary" disabled={!consent||!!busy} onClick={()=>action('自动识别并整理教材',async()=>{await api(prefix+'/prepare',{online,consent:true});await refresh();})}><RefreshCw size={15}/>自动整理全书 / 继续</button>}</div></div>
 <div className="review-layout"><aside className="review-directory" aria-label="教材复习目录"><div className="review-search"><Search size={15}/><input aria-label="搜索复习章节" placeholder="搜索章节、知识点" value={search} onChange={e=>setSearch(e.target.value)}/></div>{chapters.map(chapter=><details key={chapter} open><summary>{chapter}</summary>{visible.filter((u:any)=>u.chapter===chapter).map((u:any)=><button key={u.id} className={u.id===current?.id?'selected':''} aria-current={u.id===current?.id?true:undefined} onClick={()=>choose(u)}><span>{u.number==='intro'||u.number.startsWith('c')||u.number.startsWith('ocr')?'':u.number+' '}{u.title}</span><small>{u.lesson?.status==='CANDIDATE_REVIEWED'?'已整理':'待整理'}</small></button>)}</details>)}{data.units.length>0&&!visible.length&&<p className="muted" role="status">未找到匹配章节，试试更短的关键词。</p>}{!data.units.length&&<p className="muted">扫描教材尚未识别。设置视觉模型后可自动整理。</p>}</aside>
 <article className="review-lesson" onMouseUp={()=>{const text=window.getSelection()?.toString().trim();if(text&&current)onAsk({...current,selectOnly:true},text.slice(0,10000));}}>{current?<><div className="eyebrow">{current.chapter}</div><h2>{current.number==='intro'||current.number.startsWith('c')||current.number.startsWith('ocr')?'':current.number+' '}{current.title}</h2><div className="lesson-actions"><button className="primary" disabled={!consent||!!busy||data.active} onClick={()=>action('整理本节复习详解',async()=>{await poll((await api(prefix+'/generate',{unit:current.id,online,force:!!lesson,consent:true})).task);await refresh();})}><BookOpen size={15}/>{lesson?'重新整理本节':'生成本节详解'}</button><button className="secondary" onClick={()=>onAsk(current)}><MessageCircle size={15}/>问这一节</button></div>
 <section className="textbook-conversion"><h3>教材原有定义、定理与完整内容</h3><p className="muted">当前部分共 {current.blocks?.length??0} 个原文条目，按教材顺序保留。正式定义使用原文，不用 AI 概括替代。可靠提取的原文自动进入教材知识层；只对具体解析疑点请求核对，AI 教学另行独立审核。</p>{current.blocks?.map((block:any,index:number)=><details className="textbook-block" key={block.id} open={index===0||['定义','定理','公理'].includes(block.kind)}><summary><span className="badge">{block.kind}</span> {block.title==='教材正文'?'概念说明与教材正文':block.title}<span className="badge">{block.status==='NEEDS_VERIFY'?'局部识别待核对':'已进入教材知识层'}</span></summary><div className="prose">{renderText(block.formatted??block.content)}</div>{block.mathIssues.map((issue:string,i:number)=><p className="error" key={i}>{issue}</p>)}<button className="text-button" onClick={()=>onAsk(current,block.content)}>这段定义或推导，问 AI</button><button className="text-button" onClick={()=>onSource(block.source.pdfIndex)}>核对教材原文</button></details>)}</section>
 <h3>AI 深度教学与知识联系</h3>{lesson?.status==='CANDIDATE_REVIEWED'&&<nav className="learning-node-map" aria-label="本节学习节点">{lesson.concepts.map((c:any,i:number)=><a href={'#learning-node-'+i} key={i}><span>{focusNames[c.focus]??'概念'}</span>{c.title}</a>)}</nav>}
 {lesson?.status==='CANDIDATE_REVIEWED'?<><div className="review-trust"><ShieldCheck size={16}/>AI 深度讲解 · 独立审查通过 · 原文与讲解分层保留</div><div className="prose lesson-summary">{renderText(lesson.summary)}</div>{lesson.concepts.map((concept:any,i:number)=><section className="concept-card" id={'learning-node-'+i} key={i}><div className="concept-number">{String(i+1).padStart(2,'0')}</div><div><span className="badge">{focusNames[concept.focus]??'概念'} · AI 教学</span><h3>{concept.title}</h3><div className="prose">{renderText(concept.body)}</div>{concept.symbols?.length>0&&<dl className="learning-symbols">{concept.symbols.map((item:any)=><React.Fragment key={item.symbol}><dt>{renderText('$'+item.symbol+'$')}</dt><dd>{item.meaning}</dd></React.Fragment>)}</dl>}{concept.relations?.length>0&&<details><summary>前置知识与关联依据</summary>{concept.relations.map((rel:any,j:number)=><p className="muted" key={j}>{rel.reason} · {current.blocks.find((b:any)=>b.id===rel.targetSourceId)?.title??rel.targetSourceId}</p>)}</details>}<div className="concept-actions"><button className="text-button" onClick={()=>onAsk(current,concept.body.slice(0,10000))}>这一步没懂，问 AI<ArrowRight size={14}/></button>{concept.webIds.length>0&&<span className="badge">含联网补充</span>}</div></div></section>)}{[['易错点',lesson.mistakes],['试着自己回答',lesson.checks],['仍需核对的缺漏',lesson.gaps]].map(([title,items]:any)=>items.length>0&&<section className="lesson-notes" key={title}><h3>{title}</h3>{items.map((text:string,i:number)=><div className="prose" key={i}>{renderText(text)}</div>)}</section>)}{lesson.warnings.map((text:string)=><p className="muted" key={text}>{text}</p>)}{lesson.sources.length>0&&<details className="lesson-sources"><summary>联网资料来源与版本匹配状态</summary>{lesson.sources.map((s:any)=><div key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><span className="badge">{s.kind}</span><p>{s.url}</p><p>{s.license??s.excerpt}</p></div>)}</details>}</>:lesson?<div className="review-warning"><strong>本节详解未通过审查，需要修订</strong><p>{lesson.review.issues.join('；')}</p></div>:<div className="lesson-empty"><BookOpen size={30}/><h3>把本节教材整理成可以学习的详解</h3><p>包括定义与符号解释、适用条件、逐步推导、具体例子、易错点和自测。勾选上方模型使用同意后，生成本节或自动整理全书。</p></div>}
 <button className="text-button" onClick={()=>onSource(current.sourcePage??1)}>打开教材原件核对</button></>:<div className="lesson-empty"><BookOpen size={30}/><h3>先识别教材内容</h3><p>文字 PDF 自动提取，扫描 PDF 使用视觉模型。识别有进度，可以暂停和继续。</p></div>}</article></div></div>;
}
