import React,{useEffect,useState} from 'react';
import {BookOpen,MessageCircle,RefreshCw,Search,ShieldCheck,Pause,ArrowRight} from 'lucide-react';

export default function StudyWorkbench({workspace,api,action,poll,renderText,onAsk,onSource,busy}:{workspace:string;api:(u:string,b?:any)=>Promise<any>;action:(label:string,fn:()=>Promise<void>)=>Promise<void>;poll:(task:string)=>Promise<any>;renderText:(text:string)=>React.ReactNode;onAsk:(unit:any,text?:string)=>void;onSource:(page:number)=>void;busy:string}){
 const [data,setData]=useState<any>({units:[]});const [unit,setUnit]=useState('');const [search,setSearch]=useState('');const [consent,setConsent]=useState(false);const [online,setOnline]=useState(true);
 const prefix=`/workspaces/${workspace}/study`;
 async function refresh(){const result=await api(prefix);setData(result);setUnit(old=>result.units.some((u:any)=>u.id===old)?old:result.units[0]?.id||'');}
 useEffect(()=>{let gone=false;api(prefix).then(result=>{if(!gone){setData(result);setUnit(localStorage.getItem('study-unit:'+workspace)||result.units[0]?.id||'');}}).catch(()=>{});const timer=setInterval(()=>api(prefix).then(result=>{if(!gone)setData(result);}).catch(()=>{}),3000);return()=>{gone=true;clearInterval(timer);};},[workspace]);
 const current=data.units.find((u:any)=>u.id===unit)??data.units[0];const lesson=current?.lesson;const visible=data.units.filter((u:any)=>!search||(u.number+' '+u.title+' '+u.chapter).includes(search));const chapters=[...new Set(visible.map((u:any)=>u.chapter))] as string[];
 const choose=(u:any)=>{setUnit(u.id);localStorage.setItem('study-unit:'+workspace,u.id);};
 return <div className="review-workbench"><div className="study-heading"><div><div className="eyebrow">从教材识别到复习详解</div><h1>教材知识点复习</h1><p className="muted">按章节学习，解释符号、条件和每一步推导。原文保留为对照资料。</p></div><button className="primary" disabled={!current} onClick={()=>onAsk(current)}><MessageCircle size={16}/>AI 问答</button></div>
 <div className="study-pipeline"><div><strong>{data.active?'正在自动整理：'+(data.current??'识别教材'):'识别教材 → 整理知识点 → 联网补充 → 独立审查'}</strong><p>{data.completed??0} / {data.total??data.units.length} 节已整理。扫描页调用视觉模型；文字页直接解析。{data.recognitionMissing>0?` 尚有 ${data.recognitionMissing} 页识别未完成。`:null}</p>{data.lastError&&<p className="error">{data.lastError}</p>}</div><div className="pipeline-controls"><label className="consent"><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/>联网查书目信息和概念资料</label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意发送教材片段给模型，承担识别与整理费用</label>{data.active?<button className="secondary" onClick={()=>action('暂停自动整理',async()=>{await api(prefix+'/pause',{});await refresh();})}><Pause size={15}/>当前步骤后暂停</button>:<button className="secondary" disabled={!consent||!!busy} onClick={()=>action('自动识别并整理教材',async()=>{await api(prefix+'/prepare',{online,consent:true});await refresh();})}><RefreshCw size={15}/>自动整理全书 / 继续</button>}</div></div>
 <div className="review-layout"><aside className="review-directory" aria-label="教材复习目录"><div className="review-search"><Search size={15}/><input aria-label="搜索复习章节" placeholder="搜索章节、知识点" value={search} onChange={e=>setSearch(e.target.value)}/></div>{chapters.map(chapter=><details key={chapter} open><summary>{chapter}</summary>{visible.filter((u:any)=>u.chapter===chapter).map((u:any)=><button key={u.id} className={u.id===current?.id?'selected':''} onClick={()=>choose(u)}><span>{u.number.startsWith('c')||u.number.startsWith('ocr')?'':u.number+' '}{u.title}</span><small>{u.lesson?.status==='CANDIDATE_REVIEWED'?'已整理':'待整理'}</small></button>)}</details>)}{!data.units.length&&<p className="muted">扫描教材尚未识别。设置视觉模型后可自动整理。</p>}</aside>
 <article className="review-lesson" onMouseUp={()=>{const text=window.getSelection()?.toString().trim();if(text&&current)onAsk({...current,selectOnly:true},text.slice(0,10000));}}>{current?<><div className="eyebrow">{current.chapter}</div><h2>{current.number.startsWith('c')||current.number.startsWith('ocr')?'':current.number+' '}{current.title}</h2><div className="lesson-actions"><button className="primary" disabled={!consent||!!busy||data.active} onClick={()=>action('整理本节复习详解',async()=>{await poll((await api(prefix+'/generate',{unit:current.id,online,force:!!lesson,consent:true})).task);await refresh();})}><BookOpen size={15}/>{lesson?'重新整理本节':'生成本节详解'}</button><button className="secondary" onClick={()=>onAsk(current)}><MessageCircle size={15}/>问这一节</button></div>
 {lesson?.status==='CANDIDATE_REVIEWED'?<><div className="review-trust"><ShieldCheck size={16}/>AI 复习草稿 · 独立审查通过 · 识别原文待人工核验</div><div className="prose lesson-summary">{renderText(lesson.summary)}</div>{lesson.concepts.map((concept:any,i:number)=><section className="concept-card" key={i}><div className="concept-number">{String(i+1).padStart(2,'0')}</div><div><h3>{concept.title}</h3><div className="prose">{renderText(concept.body)}</div><div className="concept-actions"><button className="text-button" onClick={()=>onAsk(current,concept.body.slice(0,10000))}>这一步没懂，问 AI<ArrowRight size={14}/></button>{concept.webIds.length>0&&<span className="badge">含联网补充</span>}</div></div></section>)}{[['易错点',lesson.mistakes],['试着自己回答',lesson.checks],['仍需核对的缺漏',lesson.gaps]].map(([title,items]:any)=>items.length>0&&<section className="lesson-notes" key={title}><h3>{title}</h3>{items.map((text:string,i:number)=><div className="prose" key={i}>{renderText(text)}</div>)}</section>)}{lesson.warnings.map((text:string)=><p className="muted" key={text}>{text}</p>)}{lesson.sources.length>0&&<details className="lesson-sources"><summary>联网资料来源与版本匹配状态</summary>{lesson.sources.map((s:any)=><div key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><span className="badge">{s.kind}</span><p>{s.url}</p><p>{s.license??s.excerpt}</p></div>)}</details>}</>:lesson?<div className="review-warning"><strong>本节详解未通过审查，需要修订</strong><p>{lesson.review.issues.join('；')}</p></div>:<div className="lesson-empty"><BookOpen size={30}/><h3>把本节教材整理成可以学习的详解</h3><p>包括定义与符号解释、适用条件、逐步推导、具体例子、易错点和自测。勾选上方模型使用同意后，生成本节或自动整理全书。</p></div>}
 <button className="text-button" onClick={()=>onSource(current.sourcePage??1)}>打开教材原件核对</button></>:<div className="lesson-empty"><BookOpen size={30}/><h3>先识别教材内容</h3><p>文字 PDF 自动提取，扫描 PDF 使用视觉模型。识别有进度，可以暂停和继续。</p></div>}</article></div></div>;
}
