import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,existsSync,cpSync} from 'node:fs';
import path from 'node:path';
import {generateKeyPairSync,sign} from 'node:crypto';
import {Store,contained,id,now,hash} from '../app/server/store.js';
import {mathErrors,configure,publicSettings,context,review,generateKnowledge,vision,tutor} from '../app/server/ai.js';
import {importPDF} from '../app/server/pdf.js';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {canonical,verifyManifest,newer,selectUpdate,programPath} from '../app/server/updates.js';
import {installPrepared,recover} from '../automation/updater.mjs';

const work=path.resolve('work/tests');mkdirSync(work,{recursive:true});
const temporary=()=>mkdtempSync(path.join(work,'case-'));
function fixture(store:Store){const workspace=id();store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)',workspace,'TEST FIXTURE — not a real textbook',id(),'data/test.pdf',now(),1);const fact=store.fact({workspace,chapter:'测试章节',kind:'定义',title:'测试定义',content:'测试教材事实：函数 f 在点 a 的极限为 L。',source:{quote:'测试教材事实',pdfIndex:1}},'VERIFIED');return {workspace,fact,kp:store.one('SELECT kp FROM facts WHERE id=?',fact).kp};}
test('事实版本不可覆盖、知识点稳定、教材相互隔离',()=>{const store=new Store(temporary());const x=fixture(store),y=fixture(store);const v2=store.fact({workspace:x.workspace,title:'修订定义',chapter:'测试章节',kind:'定义',content:'确认后的测试事实',source:{quote:'确认后的测试事实'}},'VERIFIED',x.fact);assert.equal(store.one('SELECT content FROM facts WHERE id=?',x.fact).content,'测试教材事实：函数 f 在点 a 的极限为 L。');assert.equal(store.one('SELECT kp FROM facts WHERE id=?',v2).kp,x.kp);assert.equal(store.facts(x.workspace).length,1);assert.equal(store.facts(y.workspace).length,1);assert.equal(store.audit(x.workspace).verified,1);store.close();});
test('路径越界拒绝及数据库完整备份',()=>{const root=temporary(),store=new Store(root);fixture(store);assert.throws(()=>contained(root,'../outside'));const backup=store.snapshot();assert.ok(existsSync(path.join(root,'backups',backup)));store.close();const moved=temporary();cpSync(path.join(root,'data'),path.join(moved,'data'),{recursive:true});const other=new Store(moved);assert.equal(other.all('SELECT * FROM workspaces').length,1);other.close();});
test('数学发布闸门覆盖复杂表达式及裸源码',()=>{const math=[String.raw`\lim_{x\to 0}\frac{\sin x}{x}=1`,String.raw`\int_0^1 x^2\,dx=\frac13`,String.raw`\sum_{n=1}^{\infty}\frac1{n^2}`,String.raw`\sqrt{1+\sqrt{x}}`,String.raw`\begin{pmatrix}1&2\\3&4\end{pmatrix}`,String.raw`f(x)=\begin{cases}x&x>0\\0&x\le0\end{cases}`,String.raw`\forall\varepsilon>0,\exists\delta>0`,String.raw`\{x\in\mathbb R:x\ge0\}`,String.raw`\alpha+\beta\ne\gamma`];for(const expression of math)assert.deepEqual(mathErrors(`$$${expression}$$`),[]);assert.ok(mathErrors(String.raw`\frac{1}{2}`).length);assert.ok(mathErrors('$\\unknowncommand{x}$').length);assert.ok(mathErrors('$missing').length);});
test('PDF 文本导入、扫描页标记、重复导入保持已有记录',async()=>{const root=temporary(),store=new Store(root);const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const p=pdf.addPage();p.drawText('TEST FIXTURE - CALCULUS\n1.1 Limits\nDefinition: The limit is a property of a function.',{x:40,y:740,size:14,font,lineHeight:24});pdf.addPage();const bytes=await pdf.save();const a=await importPDF(store,bytes,'TEST FIXTURE',()=>{});const b=await importPDF(store,bytes,'TEST FIXTURE duplicate',()=>{});assert.equal(b.workspace,a.workspace);assert.equal(b.duplicate,true);assert.equal(store.all('SELECT * FROM workspaces').length,1);assert.equal(store.audit(a.workspace).unresolved.length,1);assert.ok(store.facts(a.workspace).every(f=>f.status==='NEEDS_VERIFY'));store.close();});
test('API key 仅内存、无可信事实拒绝、独立审查拒绝伪造引用',async()=>{const store=new Store(temporary());const x=fixture(store);configure({baseUrl:'http://127.0.0.1:1',textModel:'test',apiKey:'TEST_SECRET_NOT_REAL',timeout:5000,retries:0});assert.equal((publicSettings() as any).apiKey,undefined);assert.equal(publicSettings().hasKey,true);assert.throws(()=>context(store,x.workspace,'unknown'));store.close();});
test('独立模型审查、视觉候选与Tutor原始对话保留',async()=>{const store=new Store(temporary());const x=fixture(store);store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)',x.workspace,1,'TEST TEXT',600,800,'[]','NEEDS_VERIFY');const originalFetch=globalThis.fetch;let mode='valid';let calls=0;
 globalThis.fetch=(async(_url:any,options:any)=>{calls++;const body=JSON.parse(options.body);const reviewer=body.messages[0].content.includes('Reviewer');let content:any;if(reviewer)content={pass:true,issues:[],beginnerCanSolve:true,mathConsistent:true};else if(body.model==='vision-test')content={chapter:'测试章节',blocks:[{kind:'公式',title:'视觉候选',content:'测试公式',latex:'x^2'}],conflicts:['文字与图像有差异']};else content={title:'TEST AI OUTPUT',body:'这是一段明确标记的测试讲解，只用于自动测试。理解目标是检查流程与来源，不能作为真实数学教学材料。公式 $x^2$。',refs:mode==='forged'?['fake']: [x.fact]};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(content)}}]}),{status:200});}) as typeof fetch;
 try{configure({baseUrl:'http://127.0.0.1:1111',textModel:'text-test',visionModel:'vision-test',apiKey:'TEST',timeout:5000,retries:0});const result=await generateKnowledge(store,x.workspace,x.kp);assert.equal(result.status,'PUBLISHED');assert.equal(calls,2);mode='forged';await assert.rejects(()=>generateKnowledge(store,x.workspace,x.kp),/结构约定/);assert.equal(store.all('SELECT * FROM knowledge').length,1);mode='valid';const vis=await vision(store,x.workspace,1,'data:image/png;base64,dGVzdA==');assert.equal(store.one('SELECT status FROM facts WHERE id=?',vis.ids[0]).status,'NEEDS_VERIFY');await tutor(store,x.workspace,x.kp,'TEST QUESTION','TEST SELECTION');assert.equal(store.all('SELECT * FROM messages').length,2);assert.equal(store.one("SELECT body FROM messages WHERE role='user'").body,'TEST QUESTION');}finally{globalThis.fetch=originalFetch;store.close();}});
function signed(root:string,stage:string,version='1.0.1') {const {privateKey,publicKey}=generateKeyPairSync('ed25519');mkdirSync(path.join(root,'config'),{recursive:true});writeFileSync(path.join(root,'config/update-public.pem'),publicKey.export({type:'spki',format:'pem'}));const rel='app/dist/index.html';mkdirSync(path.join(stage,'app/dist'),{recursive:true});writeFileSync(path.join(stage,rel),'TEST UPDATE');const payload={version,baseVersion:'1.0.0',type:'Patch',schema:1,url:`https://github.com/Felix1451991535/calculus-workbench-v7/releases/download/v${version}/patch.zip`,sha256:'0'.repeat(64),files:[{path:rel,sha256:hash('TEST UPDATE')}],changes:['TEST'],risk:'test',databaseImpact:'none',tests:['TEST_FIXTURE'],published:now()};return {manifest:{...payload,signature:sign(null,Buffer.from(canonical(payload)),privateKey).toString('base64')},privateKey,publicKey};}
test('更新签名/版本/禁止路径及成功更新保留学习数据',()=>{const root=temporary(),stage=temporary();const store=new Store(root);fixture(store);store.close();const x=signed(root,stage);assert.ok(verifyManifest(x.manifest,String(x.publicKey.export({type:'spki',format:'pem'}))));assert.throws(()=>verifyManifest({...x.manifest,version:'9.0.0'},String(x.publicKey.export({type:'spki',format:'pem'}))));const before=hash(readFileSync(path.join(root,'data/workbench.sqlite')));const result=installPrepared(root,stage,x.manifest,{selfTest:false});assert.equal(result.state,'STABLE');assert.equal(hash(readFileSync(path.join(root,'data/workbench.sqlite'))),before);assert.equal(JSON.parse(readFileSync(path.join(root,'config/current-version.json'),'utf8')).version,'1.0.1');assert.ok(newer('1.0.10','1.0.2'));assert.ok(!newer('1.0.0','1.0.0'));});
test('失败更新与中断事务恢复稳定版本',()=>{const root=temporary(),stage=temporary();const store=new Store(root);fixture(store);store.close();const x=signed(root,stage);const before=hash(readFileSync(path.join(root,'data/workbench.sqlite')));assert.throws(()=>installPrepared(root,stage,x.manifest,{selfTest:false,injectFailure:true}));assert.equal(JSON.parse(readFileSync(path.join(root,'config/current-version.json'),'utf8')).version,'1.0.0');assert.equal(hash(readFileSync(path.join(root,'data/workbench.sqlite'))),before);writeFileSync(path.join(root,'updates/transaction.json'),JSON.stringify({state:'TESTING',previous:{version:'1.0.0',directory:'.'}}));assert.equal(recover(root),'ROLLED_BACK');});
test('跨版本选择完整签名更新，篡改及数据路径被拒绝',()=>{const x=signed(temporary(),temporary());const key=String(x.publicKey.export({type:'spki',format:'pem'}));const {signature,...payload}=x.manifest;const seal=(value:any)=>({...value,signature:sign(null,Buffer.from(canonical(value)),x.privateKey).toString('base64')});const full=seal({...payload,baseVersion:null,delivery:'full',files:[{path:'runtime/node.exe',sha256:'0'.repeat(64)}]});const main=seal({...payload,delivery:'patch',full});assert.equal(selectUpdate(main,key,'1.0.0').delivery,'patch');assert.equal(selectUpdate(main,key,'0.9.0').delivery,'full');assert.throws(()=>selectUpdate({...main,full:{...full,version:'9.0.0'}},key,'0.9.0'));assert.throws(()=>verifyManifest(seal({...payload,delivery:'full',files:[{path:'data/workbench.sqlite',sha256:'0'.repeat(64)}]}),key));assert.equal(programPath('runtime/../data/test',true),false);assert.equal(programPath('app/dist/index.html'),true);});
