import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync} from 'node:fs';import path from 'node:path';import http from 'node:http';
process.env.NODE_ENV='test';
test('HTTP 安全、密钥不回传、原始学习记录及有证据诊断',async()=>{const {createApp}=await import('../app/server/index.js');mkdirSync('work/tests',{recursive:true});const root=mkdtempSync(path.resolve('work/tests/http-'));const {app,store}=createApp(root);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.on('listening',r));const address=server.address() as any;const base=`http://127.0.0.1:${address.port}`;
 try{const s=await (await fetch(base+'/api/session')).json() as any;assert.equal((await fetch(base+'/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(base+'/api/settings',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':s.token,Origin:'https://evil.test'},body:'{}'})).status,403);
 const headers={'Content-Type':'application/json','X-Session-Token':s.token};const response=await fetch(base+'/api/settings',{method:'POST',headers,body:JSON.stringify({provider:'TEST',baseUrl:'https://api.deepseek.com',textModel:'test',apiKey:'TEST_SECRET',timeout:5000,retries:0})});assert.equal(response.status,200);const data=await response.json() as any;assert.equal(data.apiKey,undefined);assert.equal(data.hasKey,true);
 store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','TEST','test-hash','data/test.pdf',new Date().toISOString(),1);
 const invalidFact=await fetch(base+'/api/workspaces/w/facts',{method:'POST',headers,body:JSON.stringify({chapter:'TEST',kind:'公式',title:'TEST',content:'$\\unknowncommand{x}$',latex:'x^2',source:{quote:'TEST'},verified:true})});assert.equal(invalidFact.status,500);assert.equal(store.all('SELECT * FROM facts').length,0);
 const raw={title:'TEST MISTAKE',question:'TEST ONLY',dimension:'定理条件',rootCause:'遗漏条件'};const posted=await fetch(base+'/api/workspaces/w/records',{method:'POST',headers,body:JSON.stringify({kind:'mistake',kp:'test-kp',raw})});assert.equal(posted.status,200);const diagnosis=await (await fetch(base+'/api/workspaces/w/diagnosis')).json() as any[];assert.equal(diagnosis.find(d=>d.dimension==='定理条件').evidence.length,1);assert.equal(diagnosis.find(d=>d.dimension==='概念').status,'待评估');const records=await (await fetch(base+'/api/workspaces/w/records')).json() as any[];assert.deepEqual(records[0].raw,raw);
 const health=await (await fetch(base+'/api/health')).json() as any;assert.equal(health.status,'ok');const rejected=await new Promise<number>(resolve=>{http.get(base+'/api/health',{headers:{Host:'evil.test'}},r=>{r.resume();resolve(r.statusCode!);});});assert.equal(rejected,403);
 }finally{await new Promise<void>(r=>server.close(()=>r()));store.close();}
});
