import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {Store} from '../app/server/store.js';
import {buildSourceKnowledge,readBuild,saveBuild,teachingNodeId,attachTeachingGraph} from '../app/server/knowledge-build.js';
import {getStudy,studyUnits,studyMessages} from '../app/server/study.js';
import {context} from '../app/server/ai.js';
import {teachingGranularityIssues} from '../app/server/teaching-quality.js';

function fixture(){mkdirSync('work/tests',{recursive:true});const store=new Store(mkdtempSync(path.resolve('work/tests/v71-')));store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED V7.1','hash','data/test.pdf','TEST',2);mkdirSync(path.join(store.root,'data/workspaces/w/knowledge'),{recursive:true});return store;}
test('可靠原文自动纳入，损坏公式只产生局部异常，跨页证明完整保留；旧事实和记录不改写',()=>{
 const store=fixture();try{store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 数列\n1.1 极限\n定义 1.1\nFor every $\\varepsilon>0$, there is $N$.\n证明\nTake the maximum of two bounds.',600,800,'[]','EXTRACTED');store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',2,'The same bound applies to the remaining terms.\n例 1.1\nMalformed formula $\\unknown{x}$.',600,800,'[]','EXTRACTED');store.fact({workspace:'w',title:'USER',content:'Do not modify',source:{quote:'USER'}},'NEEDS_VERIFY');const before=store.facts('w');const graph=buildSourceKnowledge(store,'w');assert.equal(graph.target,'FULL_BOOK');assert.ok(graph.coverage.accepted>0);assert.equal(graph.coverage.localExceptions,1);assert.equal(graph.coverage.crossPageBlocks,1);assert.deepEqual(graph.coverage.orphanIds,[]);assert.equal(graph.coverage.complete,true);assert.ok(graph.exceptions.every((e:any)=>e.entryId));assert.deepEqual(store.facts('w'),before);assert.equal(readBuild(store,'w').sourceHash,graph.sourceHash);assert.equal(getStudy(store,'w').build.coverage.localExceptions,1);}finally{store.close();}
});
test('教材和教学ID不依赖展示标题，教学覆盖只计算当前来源且独立审核通过的内容',()=>{
 const store=fixture();try{for(let p=1;p<=2;p++)store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',p,p===1?'第一章 数列\n1.1 极限\n定义 1.1\nA sequence is a function on positive integers.':'A sequence has ordered terms.',600,800,'[]','EXTRACTED');const first=buildSourceKnowledge(store,'w');const unit=studyUnits(store,'w')[0];store.run("UPDATE pages SET text=replace(text,'1.1 极限','1.1 极限的定义') WHERE workspace='w' AND idx=1");const renamed=buildSourceKnowledge(store,'w');assert.deepEqual(first.nodes.filter((n:any)=>n.layer==='textbook').map((n:any)=>n.id),renamed.nodes.filter((n:any)=>n.layer==='textbook').map((n:any)=>n.id));assert.equal(studyUnits(store,'w')[0].id,unit.id);const concept={title:'任意标题',body:'AUTHORED',sourceIds:unit.source.map((s:any)=>s.id),focus:'definition',relations:[],symbols:[]};const currentUnit=studyUnits(store,'w')[0];const lesson={format:2,policy:'V7.1',reviewPolicy:'V7.1-review-r2',sourceHash:currentUnit.sourceHash,status:'CANDIDATE_REVIEWED',concepts:[concept]};const graph=attachTeachingGraph(store,'w',renamed,[currentUnit],{[unit.id]:lesson});assert.equal(graph.teachingCoverage.complete,true);assert.equal(graph.teachingCoverage.teachingNodes,1);assert.equal(graph.nodes.find((n:any)=>n.layer==='ai_teaching').id,teachingNodeId('w',concept.sourceIds,'definition',0));lesson.reviewPolicy='old';assert.equal(attachTeachingGraph(store,'w',renamed,[currentUnit],{[unit.id]:lesson}).teachingCoverage.teachingNodes,0);lesson.reviewPolicy='V7.1-review-r2';lesson.status='NEEDS_REVISION';assert.equal(attachTeachingGraph(store,'w',renamed,[currentUnit],{[unit.id]:lesson}).teachingCoverage.teachingNodes,0);}finally{store.close();}
});
test('旧的PDF候选可以直接用于教辅上下文，人工资料和有冲突视觉内容不能自动升级',()=>{
 const store=fixture();try{const text='A sequence assigns a real value to every positive integer.';store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,text,600,800,'[]','EXTRACTED');store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',2,'',600,800,'[]','NEEDS_VERIFY');const valid=store.fact({workspace:'w',title:'TEXT',content:text,source:{textbook:'w',quote:text,pdfIndex:1}});const fact=store.facts('w').find(f=>f.id===valid);assert.equal(context(store,'w',fact.kp).facts[0].status,'TEXTBOOK_ACCEPTED');assert.equal(store.facts('w').find(f=>f.id===valid).status,'NEEDS_VERIFY');const user=store.fact({workspace:'w',title:'USER',content:text,source:{quote:text}});assert.throws(()=>context(store,'w',store.facts('w').find(f=>f.id===user).kp),/可靠教材/);const conflict=store.fact({workspace:'w',title:'CONFLICT',content:text,source:{textbook:'w',method:'vision',pdfIndex:2,conflicts:['Cannot read formula']}});assert.throws(()=>context(store,'w',store.facts('w').find(f=>f.id===conflict).kp),/可靠教材/);assert.equal(buildSourceKnowledge(store,'w').coverage.unreadablePages.length,1);}finally{store.close();}
});
test('Reviewer声称通过也不能用一张摘要替代证明目标、策略、步骤和隐藏构造',()=>{
 const source=[{id:'proof',kind:'证明',status:'TEXTBOOK_ACCEPTED',content:'显然 the finite prefix and tail are bounded by their maximum.'}];const concepts=[{focus:'concept',sourceIds:['proof'],body:'Short summary'}];assert.equal(teachingGranularityIssues(source,concepts).length,4);const detailed=['proof_goal','proof_strategy','proof_step','hidden_step'].map(focus=>({focus,sourceIds:['proof'],body:'AUTHORED'}));assert.deepEqual(teachingGranularityIssues(source,detailed),[]);
});
test('页面待识别状态及跨缺页边界在框架、学习和缓存中一致待核对',()=>{
 const store=fixture();try{store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 极限\n1.1 数列\n证明\nProof begins here.',600,800,'[]','EXTRACTED');store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',3,'Unrelated content after a missing page.',600,800,'[]','EXTRACTED');const unit=studyUnits(store,'w')[0];assert.equal(unit.source[0].status,'NEEDS_VERIFY');assert.ok(unit.source[0].issues.some((s:string)=>s.includes('拼接边界')));store.run("UPDATE pages SET status='NEEDS_VERIFY' WHERE workspace='w' AND idx=1");assert.ok(studyUnits(store,'w')[0].source[0].issues.some((s:string)=>s.includes('视觉识别')));}finally{store.close();}
});
test('扫描教材不能把未核验个人笔记或无来源附加公式自动纳入教材',()=>{
 const store=fixture();try{store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'',600,800,'[]','NEEDS_VERIFY');store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',2,'A known source sentence.',600,800,'[]','EXTRACTED');store.fact({workspace:'w',title:'USER NOTE',content:'A note',source:{quote:'A note'}});assert.equal(studyUnits(store,'w').flatMap(u=>u.source).filter(s=>s.content==='A note').length,0);const bad=store.fact({workspace:'w',title:'ADDED FORMULA',content:'A known source sentence.',latex:'1=2',source:{textbook:'w',pdfIndex:2,quote:'A known source sentence.'}});assert.throws(()=>context(store,'w',store.facts('w').find(f=>f.id===bad).kp),/可靠教材/);}finally{store.close();}
});
test('新版稳定ID保留旧章节问答入口，旧教学缓存不能冒充V7.1审核',()=>{
 const store=fixture();try{store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 极限\n1.1 数列\nA sequence has ordered terms.',600,800,'[]','EXTRACTED');store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',2,'It assigns a value to each index.',600,800,'[]','EXTRACTED');const unit=studyUnits(store,'w')[0];store.run('INSERT INTO messages VALUES(?,?,?,?,?,?,?)','old','w','study:'+unit.legacyId,'user','MY QUESTION','RAW','TEST');assert.equal(studyMessages(store,'w','study:'+unit.id)[0].body,'MY QUESTION');const graph=buildSourceKnowledge(store,'w');const lesson={format:2,policy:'V7.1',reviewPolicy:'old',sourceHash:unit.sourceHash,status:'CANDIDATE_REVIEWED',concepts:[{title:'Old summary',body:'Old',sourceIds:unit.source.map((s:any)=>s.id)}]};assert.equal(attachTeachingGraph(store,'w',graph,[unit],{[unit.id]:lesson}).teachingCoverage.reviewedUnits,0);writeFileSync(path.join(store.root,'data/workspaces/w/knowledge/study.json'),JSON.stringify({lessons:{[unit.id]:lesson}}));assert.equal(getStudy(store,'w').units.find(u=>u.id===unit.id).lesson,null);assert.equal(getStudy(store,'w').completed,0);assert.equal(store.one('SELECT kp FROM messages WHERE id=?','old').kp,'study:'+unit.legacyId);}finally{store.close();}
});
test('人工确认后的视觉内容保留VERIFIED身份和教材学习入口；旧规则图谱必须重建',()=>{
 const store=fixture();try{for(let i=1;i<=2;i++)store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',i,'',600,800,'[]','NEEDS_VERIFY');const first=store.fact({workspace:'w',title:'SCAN',content:'Recognized text',source:{textbook:'w',method:'vision',pdfIndex:1,quote:'Recognized text',conflicts:[]}});store.fact({workspace:'w',title:'CONFIRMED',content:'Confirmed source content',source:{textbook:'w',method:'vision',pdfIndex:1,quote:'Confirmed source content',conflicts:['Historical OCR disagreement'],origin:'user'}},'VERIFIED',first);assert.ok(studyUnits(store,'w').flatMap(u=>u.source).some(s=>s.status==='VERIFIED'));const graph=buildSourceKnowledge(store,'w');assert.ok(graph.nodes.some((n:any)=>n.status==='VERIFIED'));assert.deepEqual(graph.coverage.unreadablePages,[2]);saveBuild(store,'w',{...graph,policy:'old',nodes:[],coverage:{...graph.coverage,localExceptions:99}});const rebuilt=buildSourceKnowledge(store,'w');assert.equal(rebuilt.policy,'V7.1-r3');assert.ok(rebuilt.nodes.length>0);assert.notEqual(rebuilt.coverage.localExceptions,99);}finally{store.close();}
});
