import test from 'node:test';import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync} from 'node:fs';import path from 'node:path';
import {Store} from '../app/server/store.js';import {configure} from '../app/server/ai.js';
import {studyUnits,generateStudy,studyTutor,researchSources} from '../app/server/study.js';
test('复习卡片独立审查、来源校验、缓存与候选问答不改写教材事实',async()=>{
 mkdirSync('work/tests',{recursive:true});const root=mkdtempSync(path.resolve('work/tests/study-'));const store=new Store(root);store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED TEST','hash','data/test.pdf','TEST',1);mkdirSync(path.join(root,'data/workspaces/w/knowledge'),{recursive:true});store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 Functions\n1.1 Functions\n1.1.1 Domain\n定义 1.1\nA function maps every input in its domain to exactly one output.',600,800,'[]','EXTRACTED');store.fact({workspace:'w',chapter:'TEST',title:'TEST',content:'TEST',source:{pdfIndex:1}},'NEEDS_VERIFY');const before=store.facts('w');const unit=studyUnits(store,'w')[0];const original=globalThis.fetch;let calls=0;let fabricate=false;
 globalThis.fetch=(async(_url:any,init:any)=>{calls++;const input=JSON.parse(init.body);const review=input.messages[0].content.includes('独立教材一致性');const tutor=input.messages[0].content.includes('复习问答助手');const output=review?{pass:true,issues:[],beginnerCanSolve:true,mathConsistent:true}:tutor?{title:'TEST',body:'A domain specifies the allowed inputs; every allowed input has exactly one output. Example: $f(x)=x^2$ with $x=2$ gives $f(2)=4$.',refs:[unit.source[0].id]}:{title:unit.title,summary:'Functions connect each allowed input to exactly one output.',concepts:[{title:'Domain and output',focus:'definition',body:'【教材定义】For $f(x)=x^2$, the input $x=2$ gives the unique output $4$. Domain means the set of all allowed inputs.',sourceIds:[fabricate?'invented':unit.source[0].id],webIds:[]}],mistakes:['An input cannot have two outputs.'],checks:['What is the output at input $3$?'],gaps:[]};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(output)}}]}));}) as typeof fetch;
 try{configure({baseUrl:'http://localhost:1111',textModel:'TEST',apiKey:'TEST',timeout:5000,retries:0});const lesson=await generateStudy(store,'w',unit.id,false);assert.equal(lesson.status,'CANDIDATE_REVIEWED');assert.equal(calls,2);await generateStudy(store,'w',unit.id,false);assert.equal(calls,2);assert.equal((await studyTutor(store,'w',unit.id,'What is domain?','')).status,'CANDIDATE_REVIEWED');assert.deepEqual(store.facts('w'),before);fabricate=true;store.run("UPDATE pages SET text=text||'\nadditional source' WHERE workspace='w'");await assert.rejects(generateStudy(store,'w',unit.id,false),/引用不存在/);assert.deepEqual(store.facts('w'),before);}finally{globalThis.fetch=original;store.close();}
});
test('联网失败不伪造教材补全结果',async()=>{const original=globalThis.fetch;globalThis.fetch=(async()=>{throw new Error('network unavailable');}) as typeof fetch;try{const result=await researchSources('AUTHORED BOOK','Domain');assert.equal(result.sources.length,0);assert.ok(result.warnings.length>=2);}finally{globalThis.fetch=original;}});

test('三轮教学修订保留完整教材，仅发送最新候选及审核意见，避免累积冲突旧稿',async()=>{
 mkdirSync('work/tests',{recursive:true});const root=mkdtempSync(path.resolve('work/tests/revision-'));const store=new Store(root);store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED','hash','data/test.pdf','TEST',1);mkdirSync(path.join(root,'data/workspaces/w/knowledge'),{recursive:true});store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 Functions\n1.1 Function\n定义 1.1\nA function gives every input exactly one output.',600,800,'[]','EXTRACTED');const unit=studyUnits(store,'w')[0];const original=globalThis.fetch;const inputs:any[]=[];let reviews=0;
 try{configure({baseUrl:'http://localhost:1111',textModel:'TEST',apiKey:'TEST',retries:0});globalThis.fetch=async(_url,init)=>{const request=JSON.parse(String(init?.body));const reviewer=request.messages[0].content.includes('独立教材一致性');let output:any;if(reviewer){reviews++;output={pass:reviews===3,issues:reviews<3?['AUTHORED REVISION REQUEST']:[],beginnerCanSolve:reviews===3,mathConsistent:true};}else{inputs.push(request.messages);output={title:'Function',summary:'A function gives every input exactly one output.',concepts:[{title:'Definition',focus:'definition',body:'【教材定义】A function gives every input exactly one output. This authored explanation preserves all source conditions.',sourceIds:unit.source.map((s:any)=>s.id),webIds:[]}],mistakes:[],checks:[],gaps:[]};}return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(output)}}]}));};assert.equal((await generateStudy(store,'w',unit.id,false)).status,'CANDIDATE_REVIEWED');assert.deepEqual(inputs.map(m=>m.length),[2,4,4]);assert.ok(inputs.every(m=>m[1].content===inputs[0][1].content));assert.ok(inputs.every(m=>m[0].content===inputs[0][0].content));
 }finally{globalThis.fetch=original;store.close();}
});
test('教材问答退回后自动修订，只保存一次用户原问与最终回复，教材原文不变',async()=>{
 mkdirSync('work/tests',{recursive:true});const root=mkdtempSync(path.resolve('work/tests/tutor-revision-'));const store=new Store(root);store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED','hash','data/test.pdf','TEST',1);mkdirSync(path.join(root,'data/workspaces/w/knowledge'),{recursive:true});store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 Sequence\n1.1 Limit\nA sequence has a value at every positive integer index.',600,800,'[]','EXTRACTED');const unit=studyUnits(store,'w')[0];const original=globalThis.fetch;let reviews=0;const inputs:any[]=[];
 try{configure({baseUrl:'http://localhost:1111',textModel:'TEST',apiKey:'TEST',retries:0});globalThis.fetch=async(_url,init)=>{const request=JSON.parse(String(init?.body));const reviewer=request.messages[0].content.includes('独立教材一致性');let output:any;if(reviewer){reviews++;output={pass:reviews===2,issues:reviews===1?['Check the integer boundary']:[],beginnerCanSolve:reviews===2,mathConsistent:reviews===2};}else{inputs.push(request.messages);output={title:'AUTHORED',body:reviews?'The corrected answer uses the positive integer index and includes the strict inequality justification.':'The first authored draft needs a mathematical boundary check before publication.',refs:[unit.source[0].id]};}return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(output)}}]}));};const sourceBefore=store.one('SELECT text FROM pages WHERE workspace=?','w').text;assert.equal((await studyTutor(store,'w',unit.id,'AUTHORED QUESTION','')).status,'CANDIDATE_REVIEWED');assert.equal(reviews,2);assert.deepEqual(inputs.map(m=>m.length),[2,4]);assert.ok(inputs.every(m=>JSON.parse(m[1].content).question==='AUTHORED QUESTION'));const rows=store.all('SELECT role,body,status FROM messages WHERE workspace=?','w');assert.equal(rows.length,2);assert.equal(rows[0].body,'AUTHORED QUESTION');assert.equal(rows[1].status,'CANDIDATE_REVIEWED');assert.equal(store.one('SELECT text FROM pages WHERE workspace=?','w').text,sourceBefore);
 }finally{globalThis.fetch=original;store.close();}
});
