import test from 'node:test';import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync} from 'node:fs';import path from 'node:path';
import {Store} from '../app/server/store.js';import {configure} from '../app/server/ai.js';
import {studyUnits,generateStudy,studyTutor,researchSources} from '../app/server/study.js';
test('复习卡片独立审查、来源校验、缓存与候选问答不改写教材事实',async()=>{
 mkdirSync('work/tests',{recursive:true});const root=mkdtempSync(path.resolve('work/tests/study-'));const store=new Store(root);store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED TEST','hash','data/test.pdf','TEST',1);mkdirSync(path.join(root,'data/workspaces/w/knowledge'),{recursive:true});store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 Functions\n1.1 Functions\n1.1.1 Domain\n定义 1.1\nA function maps every input in its domain to exactly one output.',600,800,'[]','EXTRACTED');store.fact({workspace:'w',chapter:'TEST',title:'TEST',content:'TEST',source:{pdfIndex:1}},'NEEDS_VERIFY');const before=store.facts('w');const unit=studyUnits(store,'w')[0];const original=globalThis.fetch;let calls=0;let fabricate=false;
 globalThis.fetch=(async(_url:any,init:any)=>{calls++;const input=JSON.parse(init.body);const review=input.messages[0].content.includes('独立教材一致性');const tutor=input.messages[0].content.includes('复习问答助手');const output=review?{pass:true,issues:[],beginnerCanSolve:true,mathConsistent:true}:tutor?{title:'TEST',body:'A domain specifies the allowed inputs; every allowed input has exactly one output. Example: $f(x)=x^2$ with $x=2$ gives $f(2)=4$.',refs:[unit.source[0].id]}:{title:unit.title,summary:'Functions connect each allowed input to exactly one output.',concepts:[{title:'Domain and output',body:'For $f(x)=x^2$, the input $x=2$ gives the unique output $4$. Domain means the set of all allowed inputs.',sourceIds:[fabricate?'invented':unit.source[0].id],webIds:[]}],mistakes:['An input cannot have two outputs.'],checks:['What is the output at input $3$?'],gaps:[]};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(output)}}]}));}) as typeof fetch;
 try{configure({baseUrl:'http://localhost:1111',textModel:'TEST',apiKey:'TEST',timeout:5000,retries:0});const lesson=await generateStudy(store,'w',unit.id,false);assert.equal(lesson.status,'CANDIDATE_REVIEWED');assert.equal(calls,2);await generateStudy(store,'w',unit.id,false);assert.equal(calls,2);assert.equal((await studyTutor(store,'w',unit.id,'What is domain?','')).status,'CANDIDATE_REVIEWED');assert.deepEqual(store.facts('w'),before);fabricate=true;store.run("UPDATE pages SET text=text||'\nadditional source' WHERE workspace='w'");await assert.rejects(generateStudy(store,'w',unit.id,false),/引用不存在/);assert.deepEqual(store.facts('w'),before);}finally{globalThis.fetch=original;store.close();}
});
test('联网失败不伪造教材补全结果',async()=>{const original=globalThis.fetch;globalThis.fetch=(async()=>{throw new Error('network unavailable');}) as typeof fetch;try{const result=await researchSources('AUTHORED BOOK','Domain');assert.equal(result.sources.length,0);assert.ok(result.warnings.length>=2);}finally{globalThis.fetch=original;}});
