import {chromium,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync,mkdtempSync} from 'node:fs';
import path from 'node:path';
import {PDFDocument,StandardFonts} from 'pdf-lib';
const root=process.cwd();mkdirSync('work/browser',{recursive:true});const isolated=mkdtempSync(path.resolve('work/browser/instance-'));const port=4328;
const server=spawn(process.execPath,['app/build/server/index.js'],{cwd:root,env:{...process.env,APP_ROOT:isolated,PORT:String(port)},windowsHide:true,stdio:'pipe'});
const results:any[]=[];let browser:any;
async function scenario(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,status:'PASS'});}catch(e:any){results.push({name,status:'FAIL',detail:e.message});throw e;}}
try{
 for(let i=0;i<60;i++){try{if((await fetch(`http://127.0.0.1:${port}/api/health`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,300));}
 browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});const errors:string[]=[];page.on('pageerror',(e:any)=>errors.push(e.message));
 await scenario('亮色首屏与中文 UI',async()=>{await page.goto(`http://127.0.0.1:${port}`);await expect(page.getByRole('heading',{name:/每一个为什么/})).toBeVisible();await page.screenshot({path:path.join(root,'UI_亮色.png'),fullPage:true});await page.keyboard.press('/');await expect(page.getByRole('dialog')).toBeVisible();const search=page.getByPlaceholder('输入概念、定理或关键词');await search.fill('TEST');await search.press('/');await expect(search).toHaveValue('TEST/');await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await scenario('暗色主题与窄屏',async()=>{await page.getByRole('button',{name:'切换暗色'}).click();await page.screenshot({path:path.join(root,'UI_暗色.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'UI_窄屏.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'切换亮色'}).click();});
 const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);pdf.addPage().drawText('TEST FIXTURE ONLY - CALCULUS\n1.1 Limit\nThis test page contains a sample statement for workflow checks.',{x:40,y:740,size:14,font,lineHeight:25});pdf.addPage();const bytes=await pdf.save();const fixture=path.join(isolated,'TEST-FIXTURE.pdf');writeFileSync(fixture,bytes);
 await scenario('浏览器导入教材并查看扫描待核验',async()=>{await page.getByRole('button',{name:'导入我的教材'}).click();await page.locator('input[type=file][accept="application/pdf,.pdf"]').first().setInputFiles(fixture);await expect(page.getByText('1 页需要辅助识别或人工核验')).toBeVisible({timeout:30000});await expect(page.getByText('TEST-FIXTURE').first()).toBeVisible();});
 await scenario('人工核验、原始记录及诊断',async()=>{await page.getByRole('button',{name:'核验',exact:true}).first().click();await page.getByRole('button',{name:'保存已核验版本'}).click();await expect(page.getByText('事实版本已保存。')).toBeVisible();await page.getByRole('button',{name:'我的错题'}).click();await page.getByRole('button',{name:'记录错题'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('标题',{exact:true}).fill('TEST FIXTURE — 条件遗漏');await dialog.getByLabel('原题或复测任务').fill('TEST FIXTURE ONLY');await dialog.getByLabel('评估维度').selectOption('定理条件');await dialog.getByLabel('根因 / 正确方法 / 复测证据').fill('TEST FIXTURE — 未检查定理条件');await dialog.getByRole('button',{name:'保存原始记录'}).click();await expect(page.getByText('学习记录已保存。')).toBeVisible();await page.getByRole('button',{name:'学习诊断'}).click();await expect(page.getByText('需要复习 · 1 条证据')).toBeVisible();});
 await scenario('设置、完整备份与公式视图',async()=>{await page.getByRole('button',{name:'设置与数据'}).click();await page.getByRole('button',{name:'创建完整备份'}).click();await expect(page.getByText('完整备份已保存，可使用恢复脚本；恢复前会再次备份现有数据。')).toBeVisible();await page.getByRole('button',{name:'教材核验',exact:false}).first().click();await page.getByRole('button',{name:'修订',exact:false}).first().click();await page.getByLabel('公式（LaTeX，可选）').fill(String.raw`\lim_{x\to0}\frac{\sin x}{x}=1`);await expect(page.locator('.formula-preview .katex')).toBeVisible();await page.screenshot({path:path.join(root,'UI_公式核验.png'),fullPage:true});await page.getByRole('button',{name:'保存已核验版本'}).click();await page.getByRole('button',{name:'教材与学习'}).click();await page.screenshot({path:path.join(root,'UI_学习页_测试夹具.png'),fullPage:true});await page.getByRole('button',{name:'查看原文'}).click();await expect(page.locator('.pdf-canvas')).toBeVisible();await expect(page.getByRole('button',{name:'视觉辅助'})).toBeEnabled({timeout:30000});await page.getByRole('button',{name:'下一页'}).click();await expect(page.getByText('2 / 2',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'视觉辅助'})).toBeEnabled({timeout:30000});await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await scenario('知识框架与批量视觉识别的同意开关',async()=>{await page.getByRole('button',{name:'教材核验',exact:true}).click();await page.getByRole('button',{name:'知识框架',exact:true}).click();await expect(page.getByRole('heading',{name:'教材知识框架',exact:true})).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'选择页范围并识别'}).click();await expect(page.getByRole('button',{name:'开始或继续识别'})).toBeDisabled();await expect(page.getByText('同意将所选页面图像发送给配置的视觉服务，并承担该服务的用量费用')).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await scenario('同书对照资料上传与实际PDF切换查看',async()=>{const reference=await PDFDocument.create();reference.addPage();reference.addPage();reference.addPage();const file=path.join(isolated,'AUTHORED-REFERENCE.pdf');writeFileSync(file,await reference.save());await page.getByRole('button',{name:'对照文件（1）'}).click();await page.locator('input[type=file][accept="application/pdf,.pdf"]').last().setInputFiles(file);await expect(page.getByText('对照原件已保存在当前教材空间。')).toBeVisible();await page.getByRole('button',{name:'AUTHORED-REFERENCE 原件对照资料'}).click();await expect(page.getByRole('button',{name:'视觉辅助'})).toBeEnabled({timeout:30000});await expect(page.getByText('1 / 3',{exact:true})).toBeVisible();await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'教材与学习'}).click();});
 await scenario('无前端异常及窄屏 Tutor',async()=>{expect(errors).toEqual([]);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开 Tutor'}).click();await expect(page.getByRole('heading',{name:'哪里还没懂？'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
}catch(e:any){console.error(e.message);process.exitCode=1;}finally{await browser?.close();server.kill();writeFileSync(path.join(root,'work/browser/acceptance.json'),JSON.stringify({created:new Date().toISOString(),fixture:'TEST FIXTURE ONLY; no user textbooks or credentials',results},null,2));console.log(JSON.stringify(results,null,2));}
