import {mkdirSync,mkdtempSync,writeFileSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {chromium} from '@playwright/test';
import {Store,now} from '../app/server/store.js';
import {importPDF} from '../app/server/pdf.js';
import {configure,generateKnowledge,tutor,vision} from '../app/server/ai.js';
import {makeQuestion,organizeRecord,structureBook} from '../app/server/learning.js';
const root=process.cwd();mkdirSync('work/live',{recursive:true});const dir=mkdtempSync(path.resolve('work/live/run-'));const store=new Store(dir);const key=process.env.LIVE_TEST_KEY;delete process.env.LIVE_TEST_KEY;
if(!key)throw new Error('实时验证需要仅驻留内存的模型密钥');
configure({provider:'DeepSeek',baseUrl:'https://api.deepseek.com',textModel:'deepseek-flash',visionModel:'deepseek-flash',apiKey:key,timeout:240000,retries:1});
const results:any[]=[];let book:any;let fact:any;
async function check(name:string,fn:()=>Promise<any>){try{const result=await fn();results.push({name,status:'PASS',detail:result});console.log(name+' PASS');return result;}catch(e:any){const message=String(e.message).replaceAll(key!,'[REDACTED]');results.push({name,status:/HTTP (401|402|403)|连接失败|超时/.test(message)?'BLOCKED':'FAIL',detail:message});console.log(name+' '+results.at(-1).status+': '+message);return null;}}
try{
 const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const p=pdf.addPage();p.drawText('AUTHORED TEST TEXTBOOK - NOT USER MATERIAL\nChapter 1: Limits\nLet f:D->R and let a be an accumulation point of D.\nDefinition: lim f(x)=L as x tends to a means:\nFor every epsilon>0 there exists delta>0 such that\nfor every x in D, 0<|x-a|<delta implies |f(x)-L|<epsilon.\nExample: D=R, lim x^2=0 as x tends to 0.\nProof: choose delta=sqrt(epsilon). Then |x|<delta implies x^2<epsilon.',{x:35,y:760,size:13,font,lineHeight:25});
 const browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:800,height:1000}});await page.setContent('<html><body style="font-family:Arial;padding:50px"><h1>AUTHORED SCANNED TEST PAGE</h1><h2>Chapter 2: Derivatives</h2><p>Definition: f\u0027(a) = lim [f(a+h)-f(a)]/h as h tends to 0.</p><p>For f(x)=x^2, the derivative at a is 2a.</p><p>Proof: [(a+h)^2-a^2]/h = 2a+h for h not equal to zero.</p><p>Taking the limit h tends to 0 yields 2a.</p><p>This page is authored only for real API acceptance testing.</p></body></html>');const image=await page.screenshot({type:'png'});await browser.close();const png=await pdf.embedPng(image);pdf.addPage([600,750]).drawImage(png,{x:0,y:0,width:600,height:750});
 const bytes=await pdf.save();writeFileSync(path.join(dir,'AUTHORED-TEST.pdf'),bytes);
 book=await check('真实数学样本：文字与扫描PDF导入',()=>importPDF(store,bytes,'AUTHORED TEST ONLY',()=>{}));if(!book)throw new Error('测试教材导入失败');
 const candidate=store.facts(book.workspace)[0];const verified=store.fact({...candidate,title:'函数极限的定义与x平方在0的极限',chapter:'第1章 极限',workspace:book.workspace,latex:String.raw`\forall\varepsilon>0\ \exists\delta>0\ \forall x\in D:\ 0<|x-a|<\delta\Rightarrow|f(x)-L|<\varepsilon`,source:{...candidate.source,chapter:'第1章 极限'}},'VERIFIED',candidate.id);fact=store.one('SELECT * FROM facts WHERE id=?',verified);
 await check('真实DeepSeek知识页与独立Reviewer',async()=>{const result=await generateKnowledge(store,book.workspace,fact.kp);if(result.status!=='PUBLISHED')throw new Error('Reviewer未通过：'+result.review.issues.join('；'));const k=store.one('SELECT * FROM knowledge WHERE id=?',result.id);writeFileSync(path.join(dir,'GENERATED_LESSON.md'),k.body);return {id:result.id,status:result.status,characters:k.body.length,review:result.review};});
 await check('真实Tutor第一轮：量词与例子',async()=>{const r=await tutor(store,book.workspace,fact.kp,'我完全没学过极限，为什么先给 epsilon 再找 delta？请用 x^2 在0的极限讲清，并给一道基础理解检查。','for every epsilon there exists delta');if(r.status!=='PUBLISHED')throw new Error('Tutor审查未通过：'+r.review.issues.join('；'));return {status:r.status,review:r.review};});
 await check('真实Tutor第二轮：改变策略',async()=>{const r=await tutor(store,book.workspace,fact.kp,'还是不懂。不要重复上一种说法，用 epsilon=0.01 的具体数字，逐步解释 delta 为什么取0.1，并检查我的理解。','delta=sqrt(epsilon)');if(r.status!=='PUBLISHED')throw new Error('Tutor审查未通过：'+r.review.issues.join('；'));return {status:r.status,review:r.review};});
 await check('真实视觉：扫描公式与候选隔离',async()=>{const result=await vision(store,book.workspace,2,'data:image/png;base64,'+image.toString('base64'));if(!result.ids.length)throw new Error('视觉返回空候选');if(result.ids.some((v:string)=>store.one('SELECT status FROM facts WHERE id=?',v).status==='VERIFIED'))throw new Error('视觉候选错误发布');return {candidates:result.ids.length,status:result.status,conflicts:result.conflicts};});
 await check('真实全书结构候选与符号隔离',()=>structureBook(store,book.workspace));
 await check('真实原创题：Generator独立Solver与Critic',async()=>{const r=await makeQuestion(store,book.workspace,fact.kp);if(r.status!=='PUBLISHED'){const q=store.one('SELECT review FROM questions WHERE id=?',r.id);throw new Error('题目未通过：'+q.review);}return r;});
 const record=crypto.randomUUID();store.run('INSERT INTO records VALUES(?,?,?,?,?,?,?)',record,book.workspace,'transcript',fact.kp,JSON.stringify({text:'老师强调：epsilon是先给定的目标误差，delta根据epsilon选取。不要交换量词顺序。以x平方在0点为例。'}),'{}',now());
 await check('真实课堂转写整理并保留原始记录',async()=>{const r=await organizeRecord(store,book.workspace,record);if(!JSON.parse(store.one('SELECT raw FROM records WHERE id=?',record).raw).text)throw new Error('原始记录丢失');return {id:r.id,claims:r.claims.length};});
}catch(e:any){console.error(String(e.message).replaceAll(key,'[REDACTED]'));process.exitCode=1;}finally{store.close();const report={created:now(),provider:'DeepSeek',textModel:'deepseek-flash',visionModel:'deepseek-flash',sample:'数学正确的自编验收样本，独立work目录；不冒充用户教材或完整教材验收。',results};writeFileSync(path.join(root,'work/live/LIVE_ACCEPTANCE.json'),JSON.stringify(report,null,2));console.log('实时验收报告已保存；未记录密钥。');if(results.some(r=>r.status==='FAIL'))process.exitCode=1;}
