import {chromium,expect} from '@playwright/test';import {createServer} from 'node:http';import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';import path from 'node:path';

process.env.NODE_ENV='test';const {configure}=await import(new URL('../app/build/server/ai.js',import.meta.url).href);const {createApp}=await import(new URL('../app/build/server/index.js',import.meta.url).href);
mkdirSync('work/study-browser',{recursive:true});const root=mkdtempSync(path.resolve('work/study-browser/run-'));const {app,store}=createApp(root);mkdirSync(path.join(root,'data/workspaces/w/knowledge'),{recursive:true});store.run('INSERT INTO workspaces VALUES(?,?,?,?,?,?)','w','AUTHORED REVIEW TEST','HASH','data/test.pdf','TEST',1);store.run('INSERT INTO pages VALUES(?,?,?,?,?,?,?)','w',1,'第一章 函数\n1.1 函数\n1.1.1 定义域\n定义 1.1\nEvery input has exactly one output. For example f(x)=x^2.',600,800,'[]','EXTRACTED');
const model=createServer(async(req,res)=>{let text='';for await(const chunk of req)text+=chunk;const request=JSON.parse(text);const input=JSON.parse(request.messages[1].content);const prompt=request.messages[0].content;let answer:any;if(prompt.includes('独立教材一致性'))answer={pass:true,issues:[],beginnerCanSolve:true,mathConsistent:true};else if(prompt.includes('复习问答助手'))answer={title:'解释定义域',body:'定义域表示允许代入的输入。对 $f(x)=x^2$，代入 $x=2$ 得到 $f(2)=4$，每个输入只有一个输出。这个例子用于检查问答与公式渲染流程。',refs:[input.facts[0].id]};else answer={title:'函数与定义域',summary:'先理解允许哪些输入，再理解输入和输出的对应关系。每一个允许输入必须恰好对应一个输出。',concepts:[{title:'定义域是什么',focus:'definition',body:'【教材定义】定义域是所有允许输入组成的集合。写 $f(x)=x^2$ 时，$x$ 表示输入，$f(x)$ 表示输出。代入 $x=2$，计算 $2^2=4$，所以 $f(2)=4$。函数要求同一个输入只对应一个输出。',sourceIds:[input.textbook[0].id],webIds:[]}],mistakes:['不能给同一个输入安排两个不同输出。'],checks:['输入 $3$，输出是 $9$。'],gaps:[]};res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(answer)}}]}));});await new Promise<void>(r=>model.listen(0,'127.0.0.1',r));configure({baseUrl:`http://127.0.0.1:${(model.address() as any).port}`,textModel:'TEST',apiKey:'TEST',timeout:10000,retries:0});const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));let browser:any;const results:any[]=[];
try{browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:960}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${(server.address() as any).port}`);await expect(page.getByRole('heading',{name:'教材知识点复习'})).toBeVisible();await expect(page.getByRole('button',{name:'生成本节详解'})).toBeDisabled();await page.getByLabel('联网查书目信息和概念资料').uncheck();await page.getByLabel('同意发送教材片段给模型，承担识别与整理费用').check();await page.getByRole('button',{name:'生成本节详解'}).click();await expect(page.getByRole('heading',{name:'定义域是什么'})).toBeVisible({timeout:30000});await expect(page.locator('.concept-card .katex').first()).toBeVisible();expect(await page.locator('.framework-source-text').count()).toBe(0);results.push({name:'复习首页章节目录、详解卡片、公式渲染与发送同意',status:'PASS'});
await page.getByRole('button',{name:'这一步没懂，问 AI'}).click();await expect(page.getByRole('heading',{name:'AI 问答',exact:true})).toBeVisible();await expect(page.locator('.selected-text')).toContainText('定义域');await page.getByLabel('我同意').count().catch(()=>0);await page.locator('.chat-compose input[type=checkbox]').check();await page.getByLabel('向 Tutor 提问').fill('为什么一个输入只能有一个输出？');await page.getByRole('button',{name:'发送问题'}).click();await expect(page.locator('.chat-message.assistant')).toContainText('代入',{timeout:30000});await expect(page.locator('.chat-label')).toContainText('复习草稿');results.push({name:'显式AI问答入口、选中内容追问与候选身份保留',status:'PASS'});
await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.getByLabel('向 Tutor 提问')).toBeVisible();await page.getByRole('button',{name:'选择复习章节'}).click();await expect(page.getByRole('heading',{name:'定义域是什么'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);results.push({name:'窄屏阅读与问答、刷新缓存、无前端异常',status:'PASS'});await page.screenshot({path:path.join(root,'study-narrow.png'),fullPage:true});await page.setViewportSize({width:1440,height:960});await page.screenshot({path:path.resolve('docs/evidence/STUDY_SCREENSHOT.png'),fullPage:true});
}finally{await browser?.close();await new Promise<void>(r=>server.close(()=>r()));await new Promise<void>(r=>model.close(()=>r()));store.close();writeFileSync('docs/evidence/STUDY_ACCEPTANCE.json',JSON.stringify({fixture:'AUTHORED LOCAL MODEL TEST; no user data or key',results},null,2));console.log(JSON.stringify(results));}
