import {existsSync,mkdirSync,mkdtempSync,readdirSync,renameSync,readFileSync,writeFileSync,cpSync} from 'node:fs';
import {spawn,execFileSync} from 'node:child_process';
import path from 'node:path';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {sign} from 'node:crypto';
import {installPrepared,canonical,digest} from './updater.mjs';
const root=process.cwd();mkdirSync('work/distribution',{recursive:true});const testRoot=mkdtempSync(path.resolve('work/distribution/run-'));const port=4339;const url=`http://127.0.0.1:${port}`;let child:any;let application='';let token='';const results:any[]=[];
async function request(route:string,body?:any){const form=body instanceof FormData;const res=await fetch(url+'/api'+route,{method:body?'POST':'GET',headers:body?{...(!form?{'Content-Type':'application/json'}:{}),'X-Session-Token':token}:{},body:body?(form?body:JSON.stringify(body)):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
async function stop(){if(!child)return;const current=child;child=null;await new Promise<void>(resolve=>{current.once('exit',()=>resolve());current.kill();});}
async function start(){const pointer=path.join(application,'config/current-version.json');const base=existsSync(pointer)?path.resolve(application,JSON.parse(readFileSync(pointer,'utf8')).directory):application;child=spawn(path.join(base,'runtime/node.exe'),[path.join(base,'app/build/server/index.js')],{cwd:application,env:{...process.env,APP_ROOT:application,PORT:String(port)},windowsHide:true,stdio:'pipe'});let stderr='';child.stderr.on('data',(x:any)=>stderr+=x.toString());for(let i=0;i<100;i++){if(child.exitCode!==null)throw new Error('发行启动失败：'+stderr);try{if((await fetch(url+'/api/health')).ok){const s=await request('/session');token=s.token;return;}}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('发行服务启动超时');}
async function check(name:string,fn:()=>Promise<any>){try{const detail=await fn();results.push({name,status:'PASS',detail});console.log(name+' PASS');return detail;}catch(e:any){results.push({name,status:'FAIL',detail:e.message});throw e;}}
try{
 await check('Windows ZIP解压与内置运行时启动',async()=>{const zip=path.join(root,'release/CalculusWorkbench-v1.0.0-Windows-x64.zip');execFileSync('powershell.exe',['-NoProfile','-Command','& {param($archive,$target) Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::ExtractToDirectory($archive,$target)}',zip,testRoot],{windowsHide:true,timeout:120000});application=path.join(testRoot,'CalculusWorkbench-v1.0.0-Windows-x64');if(!existsSync(path.join(application,'runtime/node.exe')))throw new Error('缺少运行时');await start();return await request('/health');});
 let workspace='';let backup='';let record='';
 await check('发行包实际PDF导入、备份及重启读取',async()=>{const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);pdf.addPage().drawText('AUTHORED DISTRIBUTION TEST - NOT USER DATA\nFunction f(x)=x^2 on the real numbers.\nThe limit at zero is zero.',{x:40,y:750,font,size:14,lineHeight:25});const form=new FormData();form.append('pdf',new Blob([new Uint8Array(await pdf.save())],{type:'application/pdf'}),'TEST-DISTRIBUTION.pdf');form.append('title','AUTHORED DISTRIBUTION TEST');const task=(await request('/import',form)).task;for(let i=0;i<100;i++){const t=await request('/tasks/'+task);if(t.status==='FAILED')throw new Error(t.result.error);if(t.status==='DONE'){workspace=t.result.workspace;break;}await new Promise(r=>setTimeout(r,200));}if(!workspace)throw new Error('导入超时');record=(await request(`/workspaces/${workspace}/records`,{kind:'mistake',kp:'TEST',raw:{title:'TEST DATA SENTINEL',question:'AUTHORED SAMPLE',dimension:'计算',rootCause:'TEST ONLY'},derived:{}})).id;backup=(await request('/backups',{})).name;await stop();await start();const rows=await request(`/workspaces/${workspace}/records`);if(!rows.some((r:any)=>r.id===record))throw new Error('重启记录丢失');return {workspace,backup};});
 await check('整个软件目录移动后运行与完整备份恢复',async()=>{await stop();const relocated=path.join(testRoot,'moved','CalculusWorkbench');mkdirSync(path.dirname(relocated),{recursive:true});renameSync(application,relocated);application=relocated;await start();if(!(await request(`/workspaces/${workspace}/records`)).some((r:any)=>r.id===record))throw new Error('移动后资料丢失');await stop();execFileSync(path.join(application,'runtime/node.exe'),['automation/restore.mjs',backup],{cwd:application,env:{...process.env,PORT:String(port)},timeout:60000,windowsHide:true,stdio:'pipe'});await start();if(!(await request(`/workspaces/${workspace}/records`)).some((r:any)=>r.id===record))throw new Error('恢复后资料丢失');return {restored:true,moved:true};});
 if(process.argv.includes('--online')){
  await check('实际在线签名清单检查及补丁下载',async()=>{const update=await request('/updates/check',{});if(update.status!=='AVAILABLE'||update.manifest.version!=='1.0.1')throw new Error('未发现可用1.0.1在线补丁：'+JSON.stringify(update));const task=(await request('/updates/download',{})).task;for(let i=0;i<100;i++){const t=await request('/tasks/'+task);if(t.status==='FAILED')throw new Error(t.result.error);if(t.status==='DONE')return {version:'1.0.1',status:t.result.status};await new Promise(r=>setTimeout(r,500));}throw new Error('补丁下载超时');});
  await check('实际补丁安装、候选启动自检与学习数据保留',async()=>{await stop();const stage=path.join(testRoot,'patch');execFileSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(application,'automation/Extract-SafeZip.ps1'),'-Archive',path.join(application,'updates/pending.zip'),'-Destination',stage],{timeout:60000,windowsHide:true});const manifest=JSON.parse(readFileSync(path.join(application,'updates/pending.json'),'utf8'));const result=installPrepared(application,stage,manifest);await start();const health=await request('/health');if(health.version!=='1.0.1')throw new Error('版本切换失败');if(!(await request(`/workspaces/${workspace}/records`)).some((r:any)=>r.id===record))throw new Error('更新丢失学习数据');return result;});
  await check('实际程序补丁启动失败自动回滚',async()=>{await stop();const stage=path.join(testRoot,'failed-patch');mkdirSync(path.join(stage,'app/dist'),{recursive:true});writeFileSync(path.join(stage,'app/dist/test-patch.txt'),'AUTHORED FAILED UPDATE TEST');const payload={version:'1.0.2',baseVersion:'1.0.1',type:'Patch',schema:1,url:'https://github.com/Felix1451991535/calculus-workbench-v7/releases/download/v1.0.2/test.zip',sha256:'0'.repeat(64),files:[{path:'app/dist/test-patch.txt',sha256:digest('AUTHORED FAILED UPDATE TEST')}],changes:['TEST'],risk:'TEST',databaseImpact:'none',tests:['TEST'],published:new Date().toISOString()};const privateKey=readFileSync(path.resolve(root,'../../work/release-signing/update-private.pem'));const manifest={...payload,signature:sign(null,Buffer.from(canonical(payload)),privateKey).toString('base64')};let failed=false;try{installPrepared(application,stage,manifest,{injectFailure:true});}catch{failed=true;}if(!failed)throw new Error('故障未被阻断');await start();if((await request('/health')).version!=='1.0.1')throw new Error('未恢复稳定版本');if(!(await request(`/workspaces/${workspace}/records`)).some((r:any)=>r.id===record))throw new Error('回滚丢失记录');return {state:'ROLLED_BACK',dataPreserved:true};});
  await check('基础版本不匹配时完整在线升级保留学习数据',async()=>{await stop();const old=application;const fresh=path.join(testRoot,'full-fallback');execFileSync('powershell.exe',['-NoProfile','-Command','& {param($archive,$target) Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::ExtractToDirectory($archive,$target)}',path.join(root,'release/CalculusWorkbench-v1.0.1-Windows-x64.zip'),fresh],{windowsHide:true,timeout:120000});application=path.join(fresh,'CalculusWorkbench-v1.0.1-Windows-x64');cpSync(path.join(old,'data'),path.join(application,'data'),{recursive:true});writeFileSync(path.join(application,'config/current-version.json'),JSON.stringify({version:'0.9.0',directory:'.'}));await start();const update=await request('/updates/check',{});if(update.manifest?.delivery!=='full')throw new Error('没有选择完整更新');const task=(await request('/updates/download',{})).task;let done=false;for(let i=0;i<1800;i++){const t=await request('/tasks/'+task);if(t.status==='FAILED')throw new Error(t.result.error);if(t.status==='DONE'){done=true;break;}await new Promise(r=>setTimeout(r,1000));}if(!done)throw new Error('完整更新下载超时');await stop();const stage=path.join(testRoot,'full-stage');execFileSync('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.join(application,'automation/Extract-SafeZip.ps1'),'-Archive',path.join(application,'updates/pending.zip'),'-Destination',stage,'-Full'],{timeout:120000,windowsHide:true});const manifest=JSON.parse(readFileSync(path.join(application,'updates/pending.json'),'utf8'));const result=installPrepared(application,stage,manifest);await start();if((await request('/health')).version!=='1.0.1')throw new Error('完整版本启动失败');if(!(await request(`/workspaces/${workspace}/records`)).some((r:any)=>r.id===record))throw new Error('完整更新丢失学习记录');return {...result,delivery:'full',dataPreserved:true};});

 }
}catch(e:any){console.error(e.message);process.exitCode=1;}finally{await stop();writeFileSync(path.join(root,'work/distribution/DISTRIBUTION_ACCEPTANCE.json'),JSON.stringify({created:new Date().toISOString(),results},null,2));console.log(JSON.stringify(results,null,2));}
